#!/usr/bin/env python3
"""Script to append all remaining categories"""

rest_of_data = """,
    'cities-1': [
        { word: 'New York', chord: 'TPHAOU/KWRORK' },
        { word: 'Los Angeles', chord: 'HROS/APB/SKWREL/ES' },
        { word: 'Chicago', chord: 'SHEUBG' },
        { word: 'Houston', chord: 'HAOUFT' },
        { word: 'Phoenix', chord: 'TPAOE/TPHEUBGS' },
        { word: 'Philadelphia', chord: 'TPHEUL' },
        { word: 'San Antonio', chord: 'SAPB/APB/TOEUPB/KWRO' },
        { word: 'San Diego', chord: 'SAPB/TKAOE/EG/O*' },
        { word: 'Dallas', chord: 'TKAL/AS' },
        { word: 'San Jose', chord: 'SAPB/HO/SA*EU' }
    ],
    'cities-2': [
        { word: 'Austin', chord: 'AUFPT' },
        { word: 'Jacksonville', chord: 'SKWRABG/SOPB/SREL' },
        { word: 'Fort Worth', chord: 'TPORT/WORT' },
        { word: 'Columbus', chord: 'KA/HRUPL/PWUS' },
        { word: 'Charlotte', chord: 'SHAR/HROT' },
        { word: 'Indianapolis', chord: 'EUPBD/KWRAPB/PO*L' },
        { word: 'Seattle', chord: 'SAOET' },
        { word: 'Denver', chord: 'TKEFRB' },
        { word: 'Washington', chord: 'WORBG' },
        { word: 'Boston', chord: 'PWOFT' }
    ],
    'cities-3': [
        { word: 'Nashville', chord: 'TPHAERB/SEL' },
        { word: 'Detroit', chord: 'TKRE/TROEU' },
        { word: 'Portland', chord: 'PORT/HRAPBD' },
        { word: 'Memphis', chord: 'PHEFP/KWREUS' },
        { word: 'Oklahoma City', chord: 'O*BG/HROEPL/SEUT' },
        { word: 'Las Vegas', chord: 'HRAS/SRAEGS' },
        { word: 'Louisville', chord: 'HRAOU/EUF/SEL' },
        { word: 'Baltimore', chord: 'PWAULD' },
        { word: 'Milwaukee', chord: 'PHEUL/WAU/KAOE' },
        { word: 'Albuquerque', chord: 'AL/PWAO*U/K*ERG' }
    ],
    'cities-4': [
        { word: 'Tucson', chord: 'TAOU/SOPB' },
        { word: 'Fresno', chord: 'TPRES/TPHOE' },
        { word: 'Mesa', chord: 'PHAOE/SA*' },
        { word: 'Sacramento', chord: 'SAK/RA/PHEPBT/O*' },
        { word: 'Atlanta', chord: 'AELT' },
        { word: 'Kansas City', chord: 'KAPBS/SEUT' },
        { word: 'Colorado Springs', chord: 'KO*L/O*/RA/SPREUGS' },
        { word: 'Raleigh', chord: 'RAL/KWREU' },
        { word: 'Miami', chord: 'PHAOEU/APL' },
        { word: 'Long Beach', chord: 'HROPBG/PWAOEFP' }
    ],
    'cities-5': [
        { word: 'Virginia Beach', chord: 'SREUPBG/PWAOEFP' },
        { word: 'Omaha', chord: 'O*/PHA/HA*' },
        { word: 'Oakland', chord: 'OEBG/HRAPBD' },
        { word: 'Minneapolis', chord: 'PHEUPB/KWRAPB/PO*L' },
        { word: 'Tulsa', chord: 'TAOUL/SA*' },
        { word: 'Tampa', chord: 'TAPL/PA*' },
        { word: 'Arlington', chord: 'ARL/EUPBG/TOPB' },
        { word: 'New Orleans', chord: 'TPHAOU/OR/HRAOEPBS' },
        { word: 'Wichita', chord: 'WEUFP/TA*' },
        { word: 'Cleveland', chord: 'KHRAOEFL' }
    ],
    'cities-6': [
        { word: 'Bakersfield', chord: 'PWAEUBG/ERS/TPAOEL' },
        { word: 'Aurora', chord: 'A*/ROR/A*' },
        { word: 'Anaheim', chord: 'APB/A*/HAEUPL' },
        { word: 'Honolulu', chord: 'HO/TPH*O/HRAO*U/HRAOU' },
        { word: 'Santa Ana', chord: 'SAPBT/A*/APB/A*' },
        { word: 'Riverside', chord: 'REUFR/SAOEUD' },
        { word: 'Corpus Christi', chord: 'KORP/US/KHREUFPT' },
        { word: 'Lexington', chord: 'HR*EBGS/EUPBG/TOPB' },
        { word: 'Henderson', chord: 'H*EPB/TKERPB/SOPB' },
        { word: 'Stockton', chord: 'STOBG/TOPB' }
    ],
    'cities-7': [
        { word: 'Saint Paul', chord: 'SAEUPT/PAUBL' },
        { word: 'Cincinnati', chord: 'SEUPB/SEUPB' },
        { word: 'Pittsburgh', chord: 'PEUTS' },
        { word: 'Greensboro', chord: 'TKPWRAOEPBS/PWOR/O*' },
        { word: 'Anchorage', chord: 'APB/KHOR/EUPBLG' },
        { word: 'Plano', chord: 'PHRAPB/O*' },
        { word: 'Lincoln', chord: 'HREUPBG/KOPB' },
        { word: 'Orlando', chord: 'OR/HRAPBD/O*' },
        { word: 'Irvine', chord: 'ER/SRAOEUPB' },
        { word: 'Newark', chord: 'TPHAOU/ARK' }
    ],
    'cities-8': [
        { word: 'Toledo', chord: 'TO*/HRAOE/TKO*' },
        { word: 'Durham', chord: 'TKUR/APL' },
        { word: 'Chula Vista', chord: 'KHAOU/HRA*/SREUFPT/A*' },
        { word: 'Fort Wayne', chord: 'TPORT/WAEUPB' },
        { word: 'Jersey City', chord: 'SKWRERS/SEUT' },
        { word: 'Saint Petersburg', chord: 'SAEUPT/PAOE/TERS' },
        { word: 'Laredo', chord: 'HRA/RAOE/TKO*' },
        { word: 'Madison', chord: 'PHAD/KWREU/SOPB' },
        { word: 'Chandler', chord: 'KHAPBD/HRER' },
        { word: 'Buffalo', chord: 'PWUFL/O*' }
    ],
    'cities-9': [
        { word: 'Lubbock', chord: 'HRAUB/ABG' },
        { word: 'Scottsdale', chord: 'SKOT/S/TKAEUBL' },
        { word: 'Reno', chord: 'RAOE/TPHOE' },
        { word: 'Glendale', chord: 'TKPWHREUPB/TKAEL' },
        { word: 'Gilbert', chord: 'TKPWEUL/PWERT' },
        { word: 'Winston-Salem', chord: 'WEUPB/STOPB/SA*EL' },
        { word: 'Norfolk', chord: 'TPHOR/TPOBG' },
        { word: 'Chesapeake', chord: 'KHES/A*/PAOEBG' },
        { word: 'Garland', chord: 'TKPWAR/HRAPBD' },
        { word: 'Irving', chord: 'ER/SEUFRG' }
    ],
    'cities-10': [
        { word: 'Hialeah', chord: 'HAOE/A*/HRAOE/A*' },
        { word: 'Richmond', chord: 'REUFRPLD' },
        { word: 'Boise', chord: 'PWOEUZ' },
        { word: 'Spokane', chord: 'SPO*/KAPB' },
        { word: 'Fremont', chord: 'TPRAOE/PHOPBT' },
        { word: 'Baton Rouge', chord: 'PWAT/ROPBLG' },
        { word: 'San Bernardino', chord: 'SAPB/PW*ER/TPHAR/TKAOEPB' },
        { word: 'Modesto', chord: 'PHO*/TK*ES/TO*' },
        { word: 'Fontana', chord: 'TPOPBT/APB/A*' },
        { word: 'Des Moines', chord: 'TK*E/PHOEUPBS' }
    ],
    // American States Category
    'american-states': [
        { word: 'Alabama', chord: 'AL/A*/PWAM/A*' },
        { word: 'Alaska', chord: 'A*/HRAS/KA*' },
        { word: 'Arizona', chord: 'AR/KWREU/ZOEPB/A*' },
        { word: 'Arkansas', chord: 'ARK/APB/SAU' },
        { word: 'California', chord: 'KAL/TPEUFP' },
        { word: 'Colorado', chord: 'KO*L/O*/RA/TKO*' },
        { word: 'Connecticut', chord: 'KA/TPHET/KEUT' },
        { word: 'Delaware', chord: 'TKEL/A*/WAEUR' },
        { word: 'Florida', chord: 'TPHROR' },
        { word: 'Georgia', chord: 'SKWRORPBLG/A*' },
        { word: 'Hawaii', chord: 'HA*/WAO*EU' },
        { word: 'Idaho', chord: 'AOEUD/A*/HOE' },
        { word: 'Illinois', chord: 'EULZ' },
        { word: 'Indiana', chord: 'EUPBD/KWRAPB/A*' },
        { word: 'Iowa', chord: 'AOEUL/WA*' },
        { word: 'Kansas', chord: 'KAPBS/AS' },
        { word: 'Kentucky', chord: 'KEPBT' },
        { word: 'Louisiana', chord: 'HRAOU/EUZ' },
        { word: 'Maine', chord: 'PHAEUPB' },
        { word: 'Maryland', chord: 'PHAEUPBL' },
        { word: 'Massachusetts', chord: 'PHAS' },
        { word: 'Michigan', chord: 'PHEUFP' },
        { word: 'Minnesota', chord: 'PHEUPB/KWREU/SOT/A*' },
        { word: 'Mississippi', chord: 'PHEUS/KWREUP' },
        { word: 'Missouri', chord: 'PHEUZ/OUR' },
        { word: 'Montana', chord: 'PHOPBT/APB/A*' },
        { word: 'Nebraska', chord: 'TPHE/PWRAS/KA*' },
        { word: 'Nevada', chord: 'TPHE/SRAD/A*' },
        { word: 'New Hampshire', chord: 'TPHAOU/HAPHP/SHAEUR' },
        { word: 'New Jersey', chord: 'TPHAOU/SKWRERS' },
        { word: 'New Mexico', chord: 'TPHAOU/PH*EBGS' },
        { word: 'New York', chord: 'TPHAOU/KWRORK' },
        { word: 'North Carolina', chord: 'TPHORT/KA*RL' },
        { word: 'North Dakota', chord: 'TPHORT/TKOE/KWROT/A*' },
        { word: 'Ohio', chord: 'OEPB/KWRO' },
        { word: 'Oklahoma', chord: 'O*BG/HROEPL' },
        { word: 'Oregon', chord: 'OR/TKPWOPB' },
        { word: 'Pennsylvania', chord: 'PEN' },
        { word: 'Rhode Island', chord: 'ROED/AOEUL' },
        { word: 'South Carolina', chord: 'SOUT/KA*RL' },
        { word: 'South Dakota', chord: 'SOUT/TKOE/KWROT/A*' },
        { word: 'Tennessee', chord: 'TEPB' },
        { word: 'Texas', chord: 'T*EBGS' },
        { word: 'Utah', chord: 'AOUT/AU' },
        { word: 'Vermont', chord: 'SRER/PHOPBT' },
        { word: 'Virginia', chord: 'SREUPBG' },
        { word: 'Washington', chord: 'WORBG' },
        { word: 'West Virginia', chord: 'W*EFT/SREUPBG' },
        { word: 'Wisconsin', chord: 'WEUFBG' },
        { word: 'Wyoming', chord: 'WAOEUL/O*/PHEUFRG' }
    ],
    'states-1': [
        { word: 'Alabama', chord: 'AL/A*/PWAM/A*' },
        { word: 'Alaska', chord: 'A*/HRAS/KA*' },
        { word: 'Arizona', chord: 'AR/KWREU/ZOEPB/A*' },
        { word: 'Arkansas', chord: 'ARK/APB/SAU' },
        { word: 'California', chord: 'KAL/TPEUFP' },
        { word: 'Colorado', chord: 'KO*L/O*/RA/TKO*' },
        { word: 'Connecticut', chord: 'KA/TPHET/KEUT' },
        { word: 'Delaware', chord: 'TKEL/A*/WAEUR' },
        { word: 'Florida', chord: 'TPHROR' },
        { word: 'Georgia', chord: 'SKWRORPBLG/A*' }
    ],
    'states-2': [
        { word: 'Hawaii', chord: 'HA*/WAO*EU' },
        { word: 'Idaho', chord: 'AOEUD/A*/HOE' },
        { word: 'Illinois', chord: 'EULZ' },
        { word: 'Indiana', chord: 'EUPBD/KWRAPB/A*' },
        { word: 'Iowa', chord: 'AOEUL/WA*' },
        { word: 'Kansas', chord: 'KAPBS/AS' },
        { word: 'Kentucky', chord: 'KEPBT' },
        { word: 'Louisiana', chord: 'HRAOU/EUZ' },
        { word: 'Maine', chord: 'PHAEUPB' },
        { word: 'Maryland', chord: 'PHAEUPBL' }
    ],
    'states-3': [
        { word: 'Massachusetts', chord: 'PHAS' },
        { word: 'Michigan', chord: 'PHEUFP' },
        { word: 'Minnesota', chord: 'PHEUPB/KWREU/SOT/A*' },
        { word: 'Mississippi', chord: 'PHEUS/KWREUP' },
        { word: 'Missouri', chord: 'PHEUZ/OUR' },
        { word: 'Montana', chord: 'PHOPBT/APB/A*' },
        { word: 'Nebraska', chord: 'TPHE/PWRAS/KA*' },
        { word: 'Nevada', chord: 'TPHE/SRAD/A*' },
        { word: 'New Hampshire', chord: 'TPHAOU/HAPHP/SHAEUR' },
        { word: 'New Jersey', chord: 'TPHAOU/SKWRERS' }
    ],
    'states-4': [
        { word: 'New Mexico', chord: 'TPHAOU/PH*EBGS' },
        { word: 'New York', chord: 'TPHAOU/KWRORK' },
        { word: 'North Carolina', chord: 'TPHORT/KA*RL' },
        { word: 'North Dakota', chord: 'TPHORT/TKOE/KWROT/A*' },
        { word: 'Ohio', chord: 'OEPB/KWRO' },
        { word: 'Oklahoma', chord: 'O*BG/HROEPL' },
        { word: 'Oregon', chord: 'OR/TKPWOPB' },
        { word: 'Pennsylvania', chord: 'PEN' },
        { word: 'Rhode Island', chord: 'ROED/AOEUL' },
        { word: 'South Carolina', chord: 'SOUT/KA*RL' }
    ],
    'states-5': [
        { word: 'South Dakota', chord: 'SOUT/TKOE/KWROT/A*' },
        { word: 'Tennessee', chord: 'TEPB' },
        { word: 'Texas', chord: 'T*EBGS' },
        { word: 'Utah', chord: 'AOUT/AU' },
        { word: 'Vermont', chord: 'SRER/PHOPBT' },
        { word: 'Virginia', chord: 'SREUPBG' },
        { word: 'Washington', chord: 'WORBG' },
        { word: 'West Virginia', chord: 'W*EFT/SREUPBG' },
        { word: 'Wisconsin', chord: 'WEUFBG' },
        { word: 'Wyoming', chord: 'WAOEUL/O*/PHEUFRG' }
    ],
    // Countries Category
    'countries': [
        { word: 'United States', chord: 'AOU/TPHAOEUTD/STAETS' },
        { word: 'China', chord: 'KHAOEUPB/A*' },
        { word: 'India', chord: 'EUPBD/KWRA*' },
        { word: 'Brazil', chord: 'PWRA/SEUFL' },
        { word: 'Russia', chord: 'RURB/SHA*' },
        { word: 'Japan', chord: 'SKWRA/PAPB' },
        { word: 'Mexico', chord: 'PH*EBGS' },
        { word: 'Germany', chord: 'SKWRER/PHAPB' },
        { word: 'United Kingdom', chord: 'AOU/TPHAOEUTD/KEUPBG' },
        { word: 'France', chord: 'TPRARPBS' },
        { word: 'Italy', chord: 'EUT/KWRAL' },
        { word: 'Canada', chord: 'KA/TPHAD/A*' },
        { word: 'South Korea', chord: 'SOUT/KO*R' },
        { word: 'Spain', chord: 'SPAEUPB' },
        { word: 'Australia', chord: 'AUFT' },
        { word: 'Indonesia', chord: 'EUPBD/O*/TPHAOE/SHA*' },
        { word: 'Turkey', chord: 'TURK' },
        { word: 'Saudi Arabia', chord: 'SAU/TKEU/A*/RAEUB/KWRA*' },
        { word: 'Netherlands', chord: 'TPHETH/ER/HRAPBDZ' },
        { word: 'Switzerland', chord: 'SWEUFR/HRAPBD' },
        { word: 'Argentina', chord: 'ARG/EPB/TAOEPB/A*' },
        { word: 'Poland', chord: 'POE/HRAPBD' },
        { word: 'Sweden', chord: 'SWAOEPB' },
        { word: 'Belgium', chord: 'PWEL/SKWREUPL' },
        { word: 'Thailand', chord: 'THAOEUL' },
        { word: 'Austria', chord: 'AUF/TREU/A*' },
        { word: 'Nigeria', chord: 'TPHAOEUPBLG/ER/KWRA*' },
        { word: 'Israel', chord: 'EUFR' },
        { word: 'Norway', chord: 'TPHOR/WA*EU' },
        { word: 'Ireland', chord: 'AOEURL' },
        { word: 'Egypt', chord: 'AOE/SKWREUPT' },
        { word: 'South Africa', chord: 'SOUT/AFR' },
        { word: 'Denmark', chord: 'TKEPL/ARK' },
        { word: 'Singapore', chord: 'SEUPBG/GA*/POR' },
        { word: 'Malaysia', chord: 'PHA/HRAEU/SHA*' },
        { word: 'Philippines', chord: 'TPEUL/KWEUPZ' },
        { word: 'Pakistan', chord: 'PAK/KWREU/STAPB' },
        { word: 'Chile', chord: 'KHEU/HRAOE' },
        { word: 'Finland', chord: 'TPEUPB/HRAPBD' },
        { word: 'Vietnam', chord: 'SREUT/TPHAPLT' },
        { word: 'Romania', chord: 'RO*/PHAEUPB/KWRA*' },
        { word: 'Czech Republic', chord: 'KHEBG/RE/PUBL' },
        { word: 'Portugal', chord: 'PORT/KWRAL' },
        { word: 'Greece', chord: 'TKPWRAOEFS' },
        { word: 'Iraq', chord: 'AOEURBG' },
        { word: 'New Zealand', chord: 'TPHAOU/ZAOEL' },
        { word: 'Hungary', chord: 'HUPBG/TKPWRA*EU' },
        { word: 'Algeria', chord: 'AL/SKWRAOER/KWRA*' },
        { word: 'Qatar', chord: 'KA*/TAR' },
        { word: 'Kazakhstan', chord: 'KA*/SAK/STAPB' },
        { word: 'Peru', chord: 'PER/RAOU' },
        { word: 'Ukraine', chord: 'AOUBL/KWRAEUPB' },
        { word: 'Morocco', chord: 'PHO*/ROK/O*' },
        { word: 'Ecuador', chord: 'EK/WA*/TKOR' },
        { word: 'Kuwait', chord: 'KAO*U/WAEUT' },
        { word: 'Colombia', chord: 'KO*/HRUPL/PWEU/A*' },
        { word: 'Kenya', chord: 'K*EPB/KWRA*' },
        { word: 'Ethiopia', chord: 'ETH/OE/PAOEU/A*' },
        { word: 'Bangladesh', chord: 'PWAPBG/HRA*/TKESH' },
        { word: 'Ghana', chord: 'TKPWAPB/A*' },
        { word: 'Sri Lanka', chord: 'SREU/HRAPBG/KA*' },
        { word: 'Myanmar', chord: 'PHAOEU/APB/PHAR' },
        { word: 'Venezuela', chord: 'SREPB/EZ/WEL/A*' },
        { word: 'Tanzania', chord: 'TAPB/ZAPB/KWRA*' },
        { word: 'Slovakia', chord: 'SKHROF/A*/KWRA*' },
        { word: 'Dominican Republic', chord: 'TKOPLT/RE/PUBL' },
        { word: 'Guatemala', chord: 'TKPWAT/A*/PHAL/A*' },
        { word: 'Uzbekistan', chord: 'AOUZ/PWEK/KWREU/STAPB' },
        { word: 'Bulgaria', chord: 'PWUL/TKPWAEUR/KWRA*' },
        { word: 'Croatia', chord: 'KRO*/AEU/SHA*' },
        { word: 'Costa Rica', chord: 'KO*FT/A*/RAOEBG/A*' },
        { word: 'Uruguay', chord: 'AOUR/KWRA*/TKPWA*EU' },
        { word: 'Slovenia', chord: 'SHROE/SRAOEPB/KWRA*' },
        { word: 'Lithuania', chord: 'HREUTH/WA*/TPHAOE/A*' },
        { word: 'Tunisia', chord: 'TAOU/TPHAOE/SHA*' },
        { word: 'Serbia', chord: 'SER/PWEU/A*' },
        { word: 'Panama', chord: 'PAPB/A*/PHA*' },
        { word: 'Jordan', chord: 'SKWRORD/APB' },
        { word: 'Latvia', chord: 'HRAT/SREUL/A*' },
        { word: 'Lebanon', chord: 'HREB/A*/TPHOPB' },
        { word: 'Belarus', chord: 'PWEL/A*/RAOUSZ' },
        { word: 'Paraguay', chord: 'PAR/A*/TKPWA*EU' },
        { word: 'Libya', chord: 'HREUB/KWRA*' },
        { word: 'El Salvador', chord: 'EL/SAL/SRA*/TKOR' },
        { word: 'Honduras', chord: 'HOPB/TKOUR/AS' },
        { word: 'Nepal', chord: 'TPHE/PAUBL' },
        { word: 'Cambodia', chord: 'KAPL/PWOED/KWRA*' },
        { word: 'Bolivia', chord: 'PWO*/HREUF/KWRA*' },
        { word: 'Estonia', chord: 'ES/TOEUPB/KWRA*' },
        { word: 'Afghanistan', chord: 'AF/TKPWAPB/KWREU/STAPB' },
        { word: 'Cyprus', chord: 'SAOEUP/RAOUSZ' },
        { word: 'Uganda', chord: 'AOU/TKPWAPBD/A*' },
        { word: 'Zambia', chord: 'SAPL/PWEU/A*' },
        { word: 'Senegal', chord: 'SEPB/E/TKPWAUBL' },
        { word: 'Iceland', chord: 'AOEUS/HRAPBD' },
        { word: 'Jamaica', chord: 'SKWRA/PHAEUBG/A*' },
        { word: 'Zimbabwe', chord: 'SEUPL/PWABG/WA*EU' },
        { word: 'Nicaragua', chord: 'TPHEUBG/A*/RAG/WA*' },
        { word: 'Malta', chord: 'PHAULT/A*' },
        { word: 'Luxembourg', chord: 'HRUBL/KWREUPL/PWOURG' }
    ],
    'countries-1': [
        { word: 'United States', chord: 'AOU/TPHAOEUTD/STAETS' },
        { word: 'China', chord: 'KHAOEUPB/A*' },
        { word: 'India', chord: 'EUPBD/KWRA*' },
        { word: 'Brazil', chord: 'PWRA/SEUFL' },
        { word: 'Russia', chord: 'RURB/SHA*' },
        { word: 'Japan', chord: 'SKWRA/PAPB' },
        { word: 'Mexico', chord: 'PH*EBGS' },
        { word: 'Germany', chord: 'SKWRER/PHAPB' },
        { word: 'United Kingdom', chord: 'AOU/TPHAOEUTD/KEUPBG' },
        { word: 'France', chord: 'TPRARPBS' }
    ],
    'countries-2': [
        { word: 'Italy', chord: 'EUT/KWRAL' },
        { word: 'Canada', chord: 'KA/TPHAD/A*' },
        { word: 'South Korea', chord: 'SOUT/KO*R' },
        { word: 'Spain', chord: 'SPAEUPB' },
        { word: 'Australia', chord: 'AUFT' },
        { word: 'Indonesia', chord: 'EUPBD/O*/TPHAOE/SHA*' },
        { word: 'Turkey', chord: 'TURK' },
        { word: 'Saudi Arabia', chord: 'SAU/TKEU/A*/RAEUB/KWRA*' },
        { word: 'Netherlands', chord: 'TPHETH/ER/HRAPBDZ' },
        { word: 'Switzerland', chord: 'SWEUFR/HRAPBD' }
    ],
    'countries-3': [
        { word: 'Argentina', chord: 'ARG/EPB/TAOEPB/A*' },
        { word: 'Poland', chord: 'POE/HRAPBD' },
        { word: 'Sweden', chord: 'SWAOEPB' },
        { word: 'Belgium', chord: 'PWEL/SKWREUPL' },
        { word: 'Thailand', chord: 'THAOEUL' },
        { word: 'Austria', chord: 'AUF/TREU/A*' },
        { word: 'Nigeria', chord: 'TPHAOEUPBLG/ER/KWRA*' },
        { word: 'Israel', chord: 'EUFR' },
        { word: 'Norway', chord: 'TPHOR/WA*EU' },
        { word: 'Ireland', chord: 'AOEURL' }
    ],
    'countries-4': [
        { word: 'Egypt', chord: 'AOE/SKWREUPT' },
        { word: 'South Africa', chord: 'SOUT/AFR' },
        { word: 'Denmark', chord: 'TKEPL/ARK' },
        { word: 'Singapore', chord: 'SEUPBG/GA*/POR' },
        { word: 'Malaysia', chord: 'PHA/HRAEU/SHA*' },
        { word: 'Philippines', chord: 'TPEUL/KWEUPZ' },
        { word: 'Pakistan', chord: 'PAK/KWREU/STAPB' },
        { word: 'Chile', chord: 'KHEU/HRAOE' },
        { word: 'Finland', chord: 'TPEUPB/HRAPBD' },
        { word: 'Vietnam', chord: 'SREUT/TPHAPLT' }
    ],
    'countries-5': [
        { word: 'Romania', chord: 'RO*/PHAEUPB/KWRA*' },
        { word: 'Czech Republic', chord: 'KHEBG/RE/PUBL' },
        { word: 'Portugal', chord: 'PORT/KWRAL' },
        { word: 'Greece', chord: 'TKPWRAOEFS' },
        { word: 'Iraq', chord: 'AOEURBG' },
        { word: 'New Zealand', chord: 'TPHAOU/ZAOEL' },
        { word: 'Hungary', chord: 'HUPBG/TKPWRA*EU' },
        { word: 'Algeria', chord: 'AL/SKWRAOER/KWRA*' },
        { word: 'Qatar', chord: 'KA*/TAR' },
        { word: 'Kazakhstan', chord: 'KA*/SAK/STAPB' }
    ],
    'countries-6': [
        { word: 'Peru', chord: 'PER/RAOU' },
        { word: 'Ukraine', chord: 'AOUBL/KWRAEUPB' },
        { word: 'Morocco', chord: 'PHO*/ROK/O*' },
        { word: 'Ecuador', chord: 'EK/WA*/TKOR' },
        { word: 'Kuwait', chord: 'KAO*U/WAEUT' },
        { word: 'Colombia', chord: 'KO*/HRUPL/PWEU/A*' },
        { word: 'Kenya', chord: 'K*EPB/KWRA*' },
        { word: 'Ethiopia', chord: 'ETH/OE/PAOEU/A*' },
        { word: 'Bangladesh', chord: 'PWAPBG/HRA*/TKESH' },
        { word: 'Ghana', chord: 'TKPWAPB/A*' }
    ],
    'countries-7': [
        { word: 'Sri Lanka', chord: 'SREU/HRAPBG/KA*' },
        { word: 'Myanmar', chord: 'PHAOEU/APB/PHAR' },
        { word: 'Venezuela', chord: 'SREPB/EZ/WEL/A*' },
        { word: 'Tanzania', chord: 'TAPB/ZAPB/KWRA*' },
        { word: 'Slovakia', chord: 'SKHROF/A*/KWRA*' },
        { word: 'Dominican Republic', chord: 'TKOPLT/RE/PUBL' },
        { word: 'Guatemala', chord: 'TKPWAT/A*/PHAL/A*' },
        { word: 'Uzbekistan', chord: 'AOUZ/PWEK/KWREU/STAPB' },
        { word: 'Bulgaria', chord: 'PWUL/TKPWAEUR/KWRA*' },
        { word: 'Croatia', chord: 'KRO*/AEU/SHA*' }
    ],
    'countries-8': [
        { word: 'Costa Rica', chord: 'KO*FT/A*/RAOEBG/A*' },
        { word: 'Uruguay', chord: 'AOUR/KWRA*/TKPWA*EU' },
        { word: 'Slovenia', chord: 'SHROE/SRAOEPB/KWRA*' },
        { word: 'Lithuania', chord: 'HREUTH/WA*/TPHAOE/A*' },
        { word: 'Tunisia', chord: 'TAOU/TPHAOE/SHA*' },
        { word: 'Serbia', chord: 'SER/PWEU/A*' },
        { word: 'Panama', chord: 'PAPB/A*/PHA*' },
        { word: 'Jordan', chord: 'SKWRORD/APB' },
        { word: 'Latvia', chord: 'HRAT/SREUL/A*' },
        { word: 'Lebanon', chord: 'HREB/A*/TPHOPB' }
    ],
    'countries-9': [
        { word: 'Belarus', chord: 'PWEL/A*/RAOUSZ' },
        { word: 'Paraguay', chord: 'PAR/A*/TKPWA*EU' },
        { word: 'Libya', chord: 'HREUB/KWRA*' },
        { word: 'El Salvador', chord: 'EL/SAL/SRA*/TKOR' },
        { word: 'Honduras', chord: 'HOPB/TKOUR/AS' },
        { word: 'Nepal', chord: 'TPHE/PAUBL' },
        { word: 'Cambodia', chord: 'KAPL/PWOED/KWRA*' },
        { word: 'Bolivia', chord: 'PWO*/HREUF/KWRA*' },
        { word: 'Estonia', chord: 'ES/TOEUPB/KWRA*' },
        { word: 'Afghanistan', chord: 'AF/TKPWAPB/KWREU/STAPB' }
    ],
    'countries-10': [
        { word: 'Cyprus', chord: 'SAOEUP/RAOUSZ' },
        { word: 'Uganda', chord: 'AOU/TKPWAPBD/A*' },
        { word: 'Zambia', chord: 'SAPL/PWEU/A*' },
        { word: 'Senegal', chord: 'SEPB/E/TKPWAUBL' },
        { word: 'Iceland', chord: 'AOEUS/HRAPBD' },
        { word: 'Jamaica', chord: 'SKWRA/PHAEUBG/A*' },
        { word: 'Zimbabwe', chord: 'SEUPL/PWABG/WA*EU' },
        { word: 'Nicaragua', chord: 'TPHEUBG/A*/RAG/WA*' },
        { word: 'Malta', chord: 'PHAULT/A*' },
        { word: 'Luxembourg', chord: 'HRUBL/KWREUPL/PWOURG' }
    ]
"""

# Read current words.js file
with open('words.js', 'r', encoding='utf-8') as f:
    content = f.read()

# Remove the closing }; to append more data
if content.rstrip().endswith('};'):
    content = content.rstrip()[:-2]  # Remove };

# Append the new content and close properly
content += rest_of_data + "\n};"

# Write back
with open('words.js', 'w', encoding='utf-8') as f:
    f.write(content)

print("Successfully appended all remaining categories (Cities subcategories, States, Countries)!")
