// Word bank organized by keystroke count
const wordCategories = {
    '1-keystroke': [
        { word: 'the', chord: '-T' },
        { word: 'of', chord: 'F' },
        { word: 'with', chord: 'W' },
        { word: 'be', chord: 'B' },
        { word: 'he', chord: 'E' },
        { word: 'you', chord: 'U' },
        { word: 'can', chord: 'K' },
        { word: 'is', chord: 'S-' },
        { word: 'are', chord: 'R-' }
    ],
    '2-keystrokes': [
        { word: 'I', chord: 'EU' },
        { word: 'this', chord: 'TH' },
        { word: 'have', chord: 'SR' },
        { word: "you'd", chord: 'UD' },
        { word: "you'll", chord: 'UL' },
        { word: "you're", chord: 'UR' },
        { word: "you've", chord: 'UF' },
        { word: 'were', chord: 'WR' },
        { word: 'if', chord: 'TP' },
        { word: 'would', chord: 'WO' },
        { word: 'about', chord: 'PW' },
        { word: 'could', chord: 'KO' },
        { word: 'after', chord: 'AF' },
        { word: 'easy', chord: 'EZ' },
        { word: 'ask', chord: 'SK' },
        { word: 'interest', chord: 'TR' }
    ],
    '3-keystrokes': [
        { word: 'in', chord: 'TPH' },
        { word: 'a', chord: 'AEU' },
        { word: 'that', chord: 'THA' },
        { word: 'by', chord: 'PWEU' },
        { word: 'which', chord: 'WEU' },
        { word: 'they', chord: 'THE' },
        { word: 'there', chord: 'THR' },
        { word: 'who', chord: 'WHO' },
        { word: 'other', chord: 'OER' },
        { word: 'what', chord: 'WHA' },
        { word: 'do', chord: 'TKO' },
        { word: 'two', chord: 'TWO' },
        { word: 'new', chord: 'TPHU' },
        { word: 'very', chord: 'SRE' },
        { word: 'where', chord: 'W-R' },
        { word: 'being', chord: '-BG' },
        { word: 'every', chord: 'EFR' },
        { word: 'within', chord: 'W-PB' },
        { word: 'others', chord: 'OERS' },
        { word: 'become', chord: 'PW-BG' },
        { word: 'whether', chord: 'WHR' },
        { word: 'somebody', chord: 'S-B' },
        { word: 'something', chord: 'S-G' },
        { word: 'somewhere', chord: 'SWR' },
        { word: 'question', chord: 'KWE' },
        { word: 'ever', chord: '-FR' },
        { word: 'yes', chord: 'KWRE' },
        { word: 'idea', chord: 'KWR-D' },
        { word: 'ideas', chord: 'KWR-DZ' }
    ],
    '4-keystrokes': [
        { word: 'only', chord: 'OEPBL' },
        { word: 'been', chord: 'PWPB' },
        { word: 'any', chord: 'TPHEU' },
        { word: 'said', chord: 'SAEUD' },
        { word: 'many', chord: 'PHAEPB' },
        { word: 'even', chord: 'AOEPB' },
        { word: 'through', chord: 'THRU' },
        { word: 'because', chord: 'PWAUS' },
        { word: 'before', chord: 'PW-F' },
        { word: 'upon', chord: 'POPB' },
        { word: 'without', chord: 'WOUT' }
    ],
    'lesson-1': [
        { word: 'cab', chord: 'KAB' },
        { word: 'cad', chord: 'KAD' },
        { word: 'cap', chord: 'KAP' },
        { word: 'car', chord: 'KAR' },
        { word: 'cat', chord: 'KAT' },
        { word: 'cod', chord: 'KOD' },
        { word: 'cog', chord: 'KOG' },
        { word: 'cop', chord: 'KOP' },
        { word: 'core', chord: 'KOR' },
        { word: 'cot', chord: 'KOT' },
        { word: 'cub', chord: 'KUB' },
        { word: 'cuff', chord: 'KUF' },
        { word: 'cull', chord: 'KUL' },
        { word: 'cup', chord: 'KUP' },
        { word: 'cur', chord: 'KUR' },
        { word: 'cuss', chord: 'KUS' },
        { word: 'cut', chord: 'KUT' },
        { word: 'had', chord: 'HAD' },
        { word: 'hag', chord: 'HAG' },
        { word: 'half', chord: 'HAF' },
        { word: 'has', chord: 'HAZ' },
        { word: 'hat', chord: 'HAT' },
        { word: 'head', chord: 'HED' },
        { word: 'hell', chord: 'HEL' },
        { word: 'her', chord: 'HER' },
        { word: 'hog', chord: 'HOG' },
        { word: 'hop', chord: 'HOP' },
        { word: 'hot', chord: 'HOT' },
        { word: 'hub', chord: 'HUB' },
        { word: 'huff', chord: 'HUF' },
        { word: 'hug', chord: 'HUG' },
        { word: 'hull', chord: 'HUL' },
        { word: 'hut', chord: 'HUT' },
        { word: 'keg', chord: 'KEG' },
        { word: 'pad', chord: 'PAD' },
        { word: 'pal', chord: 'PAL' },
        { word: 'pass', chord: 'PAS' },
        { word: 'pat', chord: 'PAT' },
        { word: 'peg', chord: 'PEG' },
        { word: 'pep', chord: 'PEP' },
        { word: 'pet', chord: 'PET' },
        { word: 'pod', chord: 'POD' },
        { word: 'poll', chord: 'POL' },
        { word: 'pot', chord: 'POT' },
        { word: 'pour', chord: 'POR' },
        { word: 'pub', chord: 'PUB' },
        { word: 'puff', chord: 'PUF' },
        { word: 'pug', chord: 'PUG' },
        { word: 'pull', chord: 'PULL' },
        { word: 'pup', chord: 'PUP' },
        { word: 'pus', chord: 'PUS' },
        { word: 'put', chord: 'PUT' },
        { word: 'rag', chord: 'RAG' },
        { word: 'rap', chord: 'RAP' },
        { word: 'rat', chord: 'RAT' },
        { word: 'red', chord: 'RED' },
        { word: 'roar', chord: 'ROR' },
        { word: 'rob', chord: 'ROB' },
        { word: 'rod', chord: 'ROD' },
        { word: 'roll', chord: 'ROLL' },
        { word: 'rot', chord: 'ROT' },
        { word: 'rough', chord: 'RUF' },
        { word: 'rub', chord: 'RUB' },
        { word: 'rug', chord: 'RUG' },
        { word: 'rut', chord: 'RUT' },
        { word: 'sad', chord: 'SAD' },
        { word: 'sag', chord: 'SAG' },
        { word: 'sap', chord: 'SAP' },
        { word: 'sass', chord: 'SAS' },
        { word: 'sat', chord: 'SAT' },
        { word: 'says', chord: 'SEZ' },
        { word: 'sell', chord: 'SEL' },
        { word: 'set', chord: 'SET' },
        { word: 'sob', chord: 'SOB' },
        { word: 'sop', chord: 'SOP' },
        { word: 'tab', chord: 'TAB' },
        { word: 'tad', chord: 'TAD' },
        { word: 'tag', chord: 'TAG' },
        { word: 'tap', chord: 'TAP' },
        { word: 'tar', chord: 'TAR' },
        { word: 'tell', chord: 'TEL' },
        { word: 'toll', chord: 'TOL' },
        { word: 'top', chord: 'TOP' },
        { word: 'tough', chord: 'TUF' },
        { word: 'tour', chord: 'TOR' },
        { word: 'tub', chord: 'TUB' },
        { word: 'tug', chord: 'TUG' },
        { word: 'wad', chord: 'WAD' },
        { word: 'wag', chord: 'WAG' },
        { word: 'war', chord: 'WAR' },
        { word: 'was', chord: 'WAS' },
        { word: 'web', chord: 'WEB' },
        { word: 'wed', chord: 'WED' },
        { word: 'well', chord: 'WEL' },
        { word: 'wet', chord: 'WET' },
        { word: 'wore', chord: 'WOR' }
    ],
    'dropping-unstressed-vowels': [
        { word: 'averages', chord: 'AFRGS' },
        { word: 'corrupted', chord: 'KRUPTD' },
        { word: 'effort', chord: 'EFRT' },
        { word: 'horrible', chord: 'HORBL' },
        { word: 'ruffled', chord: 'RUFLD' },
        { word: 'scaffold', chord: 'SKAFLD' },
        { word: 'scarlet', chord: 'SKARLT' },
        { word: 'scuffled', chord: 'SKUFLD' },
        { word: 'several', chord: 'SEFRL' },
        { word: 'spotted', chord: 'SPOTD' },
        { word: 'starlet', chord: 'STARLT' },
        { word: 'started', chord: 'STARTD' },
        { word: 'superb', chord: 'SPERB' },
        { word: 'suppress', chord: 'SPRES' },
        { word: 'tablet', chord: 'TABLT' },
        { word: 'tepid', chord: 'TEPD' }
    ],
    'diphthong-chords': [
        { word: 'all', chord: 'AUL' },
        { word: 'awful', chord: 'AUFL' },
        { word: 'call', chord: 'KAUL' },
        { word: 'caught', chord: 'KAUT' },
        { word: 'coil', chord: 'KOEUL' },
        { word: 'crawl', chord: 'KRAUL' },
        { word: 'hall', chord: 'HAUL' },
        { word: 'halt', chord: 'HAULT' },
        { word: 'house', chord: 'HOUS' },
        { word: 'how', chord: 'HOU' },
        { word: 'howl', chord: 'HOUL' },
        { word: 'oil', chord: 'OEUL' },
        { word: 'out', chord: 'OUT' },
        { word: 'pout', chord: 'POUT' },
        { word: 'power', chord: 'POUR' },
        { word: 'prowl', chord: 'PROUL' },
        { word: 'raw', chord: 'RAU' },
        { word: 'scald', chord: 'SKAULD' },
        { word: 'scour', chord: 'SKOUR' },
        { word: 'soil', chord: 'SOEUL' },
        { word: 'soy', chord: 'SOEU' },
        { word: 'spouse', chord: 'SPOUS' },
        { word: 'sprawl', chord: 'SPRAUL' },
        { word: 'sprout', chord: 'SPROUT' },
        { word: 'straw', chord: 'STRAU' },
        { word: 'toil', chord: 'TOEUL' },
        { word: 'tower', chord: 'TOUR' },
        { word: 'wall', chord: 'WAUL' }
    ],
    'vowel-disambiguator-chords': [
        { word: 'crew', chord: 'CRAOU' },
        { word: 'heal', chord: 'HAEL' },
        { word: 'hear', chord: 'HAER' },
        { word: 'heel', chord: 'HAOEL' },
        { word: 'here', chord: 'HAOER' },
        { word: 'hood', chord: 'HAOD' },
        { word: 'peace', chord: 'PAES' },
        { word: 'pea', chord: 'PAE' },
        { word: 'pee', chord: 'PAOE' },
        { word: 'piece', chord: 'PAOES' },
        { word: 'pool', chord: 'PAOL' },
        { word: 'read', chord: 'RAED' },
        { word: 'real', chord: 'RAEL' },
        { word: 'reed', chord: 'RAOED' },
        { word: 'reel', chord: 'RAOEL' },
        { word: 'road', chord: 'RAOD' },
        { word: 'roar', chord: 'RAOR' },
        { word: 'rode', chord: 'ROED' },
        { word: 'rude', chord: 'RAOUD' },
        { word: 'ruse', chord: 'RAOUZ' },
        { word: 'sail', chord: 'SAEUL' },
        { word: 'sale', chord: 'SAEL' },
        { word: 'school', chord: 'SKAOL' },
        { word: 'sea', chord: 'SAE' },
        { word: 'see', chord: 'SAOE' },
        { word: 'soar', chord: 'SAOR' },
        { word: 'soot', chord: 'SAOT' },
        { word: 'sore', chord: 'SOR' },
        { word: 'stair', chord: 'STAEUR' },
        { word: 'stare', chord: 'STAER' },
        { word: 'tail', chord: 'TAEUL' },
        { word: 'tale', chord: 'TAEL' },
        { word: 'tea', chord: 'TAE' },
        { word: 'tee', chord: 'TAOE' },
        { word: 'toad', chord: 'TAOD' },
        { word: 'truce', chord: 'TRAOUS' },
        { word: 'waist', chord: 'WAEUFT' },
        { word: 'ware', chord: 'WAEUR' },
        { word: 'waste', chord: 'WAEFT' },
        { word: 'wear', chord: 'WAER' },
        { word: 'wheal', chord: 'WHAEL' },
        { word: 'wheel', chord: 'WHAOEL' }
    ],
    'k-d-f-l-g-b-z-v': [
        { word: 'board', chord: 'PWAORD' },
        { word: 'bobble', chord: 'PWOBL' },
        { word: 'bored', chord: 'PWORD' },
        { word: 'bruise', chord: 'PWRAOUZ' },
        { word: 'brutal', chord: 'PWRAOULT' },
        { word: 'buyer', chord: 'PWAOEUR' },
        { word: 'cigarette', chord: 'STKPWRET' },
        { word: 'correct', chord: 'KREBGT' },
        { word: 'dabble', chord: 'TKABL' },
        { word: 'debt', chord: 'TKET' },
        { word: 'deferral', chord: 'TKEFRL' },
        { word: 'depress', chord: 'TKPRES' },
        { word: 'desire', chord: 'STKAOEUR' },
        { word: 'dessert', chord: 'STKERT' },
        { word: 'destroyed', chord: 'STKROEUD' },
        { word: 'devil', chord: 'TKEFL' },
        { word: 'double', chord: 'TKUBL' },
        { word: 'drug', chord: 'TKRUG' },
        { word: 'due', chord: 'TKAOU' },
        { word: 'duffer', chord: 'TKUFR' },
        { word: 'eke', chord: 'AOEBG' },
        { word: 'fable', chord: 'TPAEUBL' },
        { word: 'feeble', chord: 'TPAOEBЛ' },
        { word: 'feral', chord: 'TPERL' },
        { word: 'fierce', chord: 'TPAOERS' },
        { word: 'for', chord: 'TPOR' },
        { word: 'ford', chord: 'TPORD' },
        { word: 'fries', chord: 'TPRAOEUS' },
        { word: 'phrase', chord: 'TPRAEUZ' },
        { word: 'get', chord: 'TKPWET' },
        { word: 'give', chord: 'TKPWEUF' },
        { word: 'glad', chord: 'TKPWHRAD' },
        { word: 'glare', chord: 'TKPWHRAEUR' },
        { word: 'glides', chord: 'TKPWHRAOEUDZ' },
        { word: 'goblet', chord: 'TKPWOBLT' },
        { word: 'gravel', chord: 'TKPWRAFL' },
        { word: 'group', chord: 'TKPWRAOUP' },
        { word: 'guest', chord: 'TKPWEFT' },
        { word: 'guide', chord: 'TKPWAOEUD' },
        { word: 'lace', chord: 'HRAEUS' },
        { word: 'leader', chord: 'HRAOERD' },
        { word: 'leaders', chord: 'HRAOERDZ' },
        { word: 'letter', chord: 'HRERT' },
        { word: 'lovers', chord: 'HROFRS' },
        { word: 'lust', chord: 'HRUFT' },
        { word: 'quake', chord: 'KWAEUBG' },
        { word: 'rockets', chord: 'ROBGTS' },
        { word: 'sphere', chord: 'STPAOER' },
        { word: 'task', chord: 'TAFBG' },
        { word: 'vase', chord: 'SRAEUS' },
        { word: 'vile', chord: 'SRAOEUL' },
        { word: 'virus', chord: 'SRAOEURS' },
        { word: 'zag', chord: 'SA*G' },
        { word: 'zap', chord: 'SA*P' },
        { word: 'zest', chord: 'S*EFT' }
    ],
    'n-m-j-y': [
        { word: 'arm', chord: 'ARPL' },
        { word: 'average', chord: 'AFRPBLG' },
        { word: 'calmed', chord: 'KAPLD' },
        { word: 'earns', chord: 'ERPBS' },
        { word: 'edge', chord: 'EPBLG' },
        { word: 'hand', chord: 'HAPBD' },
        { word: 'harm', chord: 'HARPL' },
        { word: 'hunt', chord: 'HUPBT' },
        { word: 'jagged', chord: 'SKWRAGD' },
        { word: 'jazz', chord: 'SKWRAZ' },
        { word: 'jest', chord: 'SKWREFT' },
        { word: 'jets', chord: 'SKWRETS' },
        { word: 'job', chord: 'SKWROB' },
        { word: 'jostle', chord: 'SKWROFL' },
        { word: 'jug', chord: 'SKWRUG' },
        { word: 'just', chord: 'SKWRUFT' },
        { word: 'jut', chord: 'SKWRUT' },
        { word: 'maggot', chord: 'PHAGT' },
        { word: 'mallet', chord: 'PHALT' },
        { word: 'morals', chord: 'PHORLS' },
        { word: 'muffle', chord: 'PHUFL' },
        { word: 'must', chord: 'PHUFT' },
        { word: 'nab', chord: 'TPHAB' },
        { word: 'nag', chord: 'TPHAG' },
        { word: 'nap', chord: 'TPHAP' },
        { word: 'nerd', chord: 'TPHERD' },
        { word: 'nest', chord: 'TPHEFT' },
        { word: 'nestle', chord: 'TPHEFL' },
        { word: 'never', chord: 'TPHEFR' },
        { word: 'nod', chord: 'TPHOD' },
        { word: 'nub', chord: 'TPHUB' },
        { word: 'nut', chord: 'TPHUT' },
        { word: 'palm', chord: 'PAPL' },
        { word: 'panel', chord: 'PAPBL' },
        { word: 'parent', chord: 'PARPBT' },
        { word: 'pent', chord: 'PEPBT' },
        { word: 'porridge', chord: 'PORPBLG' },
        { word: 'purge', chord: 'PURPBLG' },
        { word: 'qualms', chord: 'KWAPLS' },
        { word: 'rant', chord: 'RAPBT' },
        { word: 'rum', chord: 'RUPL' },
        { word: 'smuggle', chord: 'SPHULG' },
        { word: 'storage', chord: 'STORPBLG' },
        { word: 'stun', chord: 'STUPB' },
        { word: 'tempt', chord: 'TEPLT' },
        { word: 'term', chord: 'TERPL' },
        { word: 'trudge', chord: 'TRUPBLG' },
        { word: 'urge', chord: 'URPBLG' },
        { word: 'went', chord: 'WEPBT' },
        { word: 'yard', chord: 'KWRARD' },
        { word: 'yet', chord: 'KWRET' },
        { word: 'yurt', chord: 'KWRURT' }
    ],
    'combo-1': [
        { word: 'allowance', chord: 'HROUPBS' },
        { word: 'announce', chord: 'TPHOUPBS' },
        { word: 'blame', chord: 'PWHRAE' },
        { word: 'cement', chord: 'SPHEPBT' },
        { word: 'commit', chord: 'KPHEUT' },
        { word: 'commend', chord: 'KPHEPBD' },
        { word: 'dance', chord: 'TKAPBS' },
        { word: 'deference', chord: 'TKEFRPBS' },
        { word: 'demand', chord: 'TKPHAPBD' },
        { word: 'design', chord: 'STKAOEUPB' },
        { word: 'different', chord: 'TKEUFRPBT' },
        { word: 'diner', chord: 'TKAOEURPB' },
        { word: 'dinner', chord: 'TKEURPB' },
        { word: 'donor', chord: 'TKOERPB' },
        { word: 'dream', chord: 'TKRAOEPL' },
        { word: 'enacts', chord: 'TPHABGTS' },
        { word: 'flaunt', chord: 'TPHRAUPBT' },
        { word: 'forms', chord: 'TPORPLS' },
        { word: 'germ', chord: 'SKWRERPL' },
        { word: 'gleans', chord: 'TKPWHRAOEPBS' },
        { word: 'gnome', chord: 'TPHOEPL' },
        { word: 'grant', chord: 'TKPWRAPBT' },
        { word: 'grunt', chord: 'TKPWRUPBT' },
        { word: 'gym', chord: 'SKWREUPL' },
        { word: 'hermit', chord: 'HERPLT' },
        { word: 'inhibit', chord: 'TPHEUBT' },
        { word: 'jam', chord: 'SKWRAPL' },
        { word: 'knack', chord: 'TPHABG' },
        { word: 'knock', chord: 'TPHOBG' },
        { word: 'known', chord: 'TPHOEPB' },
        { word: 'learned', chord: 'HRERPBD' },
        { word: 'lend', chord: 'HREPBD' },
        { word: 'loin', chord: 'HROEUPB' },
        { word: 'maim', chord: 'PHAEUPL' },
        { word: 'matter', chord: 'PHAEURT' },
        { word: 'mound', chord: 'PHOUPBD' },
        { word: 'mourn', chord: 'PHOURPB' },
        { word: 'named', chord: 'TPHAEUPLD' },
        { word: 'neck', chord: 'TPHEBG' },
        { word: 'neural', chord: 'TPHAOURL' },
        { word: 'noise', chord: 'TPHOEUS' },
        { word: 'notes', chord: 'TPHOETS' },
        { word: 'noun', chord: 'TPHOUPB' },
        { word: 'novice', chord: 'TPHOFS' },
        { word: 'nudge', chord: 'TPHUPBLG' },
        { word: 'plumb', chord: 'PHRUPL' },
        { word: 'primed', chord: 'PRAOEUPLD' },
        { word: 'rhymes', chord: 'RAOEUPLS' },
        { word: 'semester', chord: 'SPHEFRT' },
        { word: 'serum', chord: 'SAOERPL' },
        { word: 'severance', chord: 'SEFRPBS' },
        { word: 'smudge', chord: 'SPHUPBLG' },
        { word: 'smuggle', chord: 'SPHULG' },
        { word: 'snide', chord: 'STPHAOEUD' },
        { word: 'time', chord: 'TAOEUPL' },
        { word: 'winner', chord: 'WEURPB' }
    ],
    'digraphs': [
        { word: 'anger', chord: 'ARPBG' },
        { word: 'ash', chord: 'ARB' },
        { word: 'catch', chord: 'KAFP' },
        { word: 'chaff', chord: 'KHAF' },
        { word: 'chart', chord: 'KHART' },
        { word: 'chat', chord: 'KHAT' },
        { word: 'chess', chord: 'KHES' },
        { word: 'chest', chord: 'KHEFT' },
        { word: 'chop', chord: 'KHOP' },
        { word: 'chore', chord: 'KHOR' },
        { word: 'crash', chord: 'KRARB' },
        { word: 'crush', chord: 'KRURB' },
        { word: 'crutch', chord: 'KRUFP' },
        { word: 'earth', chord: '*ERT' },
        { word: 'etch', chord: 'EFP' },
        { word: 'hash', chord: 'HARB' },
        { word: 'hatch', chord: 'HAFP' },
        { word: 'hath', chord: 'HA*T' },
        { word: 'health', chord: 'H*ELT' },
        { word: 'hush', chord: 'HURB' },
        { word: 'hutch', chord: 'HUFP' },
        { word: 'oath', chord: 'O*ET' },
        { word: 'orange', chord: 'ORPBG' },
        { word: 'patch', chord: 'PAFP' },
        { word: 'path', chord: 'PA*T' },
        { word: 'posh', chord: 'PORB' },
        { word: 'prong', chord: 'PROPBG' },
        { word: 'push', chord: 'PURB' },
        { word: 'rang', chord: 'RAPBG' },
        { word: 'rash', chord: 'RARB' },
        { word: 'ratchet', chord: 'RAFPT' },
        { word: 'retch', chord: 'REFP' },
        { word: 'rung', chord: 'RUPBG' },
        { word: 'rush', chord: 'RURB' },
        { word: 'shall', chord: 'SHAL' },
        { word: 'shell', chord: 'SHEL' },
        { word: 'shore', chord: 'SHOR' },
        { word: 'shovels', chord: 'SHOFLS' },
        { word: 'shuffled', chord: 'SHUFLD' },
        { word: 'sketch', chord: 'SKEFP' },
        { word: 'song', chord: 'SOPBG' },
        { word: 'sponge', chord: 'SPOPBG' },
        { word: 'squash', chord: 'SKWARB' },
        { word: 'stash', chord: 'STARB' },
        { word: 'storing', chord: 'STORPBG' },
        { word: 'stretch', chord: 'STREFP' },
        { word: 'strong', chord: 'STROPBG' },
        { word: 'stung', chord: 'STUPBG' },
        { word: 'such', chord: 'SUFP' },
        { word: 'thefts', chord: 'THEFTS' },
        { word: 'thud', chord: 'THUD' },
        { word: 'thug', chord: 'THUG' },
        { word: 'thus', chord: 'THUS' },
        { word: 'tongue', chord: 'TUPBG' },
        { word: 'touch', chord: 'TUFP' },
        { word: 'trash', chord: 'TRARB' },
        { word: 'troth', chord: 'TRO*T' },
        { word: 'twang', chord: 'TWAPBG' },
        { word: 'wash', chord: 'WARB' },
        { word: 'watch', chord: 'WAFP' },
        { word: 'wealth', chord: 'W*ELT' },
        { word: 'worth', chord: 'WO*RT' }
    ],
    'combo-2': [
        { word: 'birth', chord: 'PW*EURT' },
        { word: 'bleach', chord: 'PWHRAOEFP' },
        { word: 'blithe', chord: 'PWHRAO*EUT' },
        { word: 'blush', chord: 'PWHRURB' },
        { word: 'botch', chord: 'PWOFP' },
        { word: 'breath', chord: 'PWR*ET' },
        { word: 'brush', chord: 'PWRURB' },
        { word: 'bush', chord: 'PWURB' },
        { word: 'chance', chord: 'KHAPBS' },
        { word: 'channel', chord: 'KHAPBL' },
        { word: 'chant', chord: 'KHAPBT' },
        { word: 'charm', chord: 'KHARPL' },
        { word: 'chasm', chord: 'KHAFPL' },
        { word: 'check', chord: 'KHEBG' },
        { word: 'cherub', chord: 'KHERB' },
        { word: 'chin', chord: 'KHEUPB' },
        { word: 'chive', chord: 'KHAOEUF' },
        { word: 'choose', chord: 'KHAOS' },
        { word: 'chuck', chord: 'KHUBG' },
        { word: 'churn', chord: 'KHURPB' },
        { word: 'death', chord: 'TK*ET' },
        { word: 'ditch', chord: 'TKEUFP' },
        { word: 'fetch', chord: 'TPEFP' },
        { word: 'fifth', chord: 'TP*EUFT' },
        { word: 'fish', chord: 'TPEURB' },
        { word: 'fresh', chord: 'TPRERB' },
        { word: 'glitch', chord: 'TKPWHREUFP' },
        { word: 'growth', chord: 'TKPWHRO*ET' },
        { word: 'lash', chord: 'HRARB' },
        { word: 'latch', chord: 'HRAFP' },
        { word: 'leech', chord: 'HRAOEFP' },
        { word: 'mash', chord: 'PHARB' },
        { word: 'match', chord: 'PHAFP' },
        { word: 'math', chord: 'PHA*T' },
        { word: 'mesh', chord: 'PHERB' },
        { word: 'method', chord: 'PH*ETD' },
        { word: 'much', chord: 'PHUFP' },
        { word: 'plush', chord: 'PHRURB' },
        { word: 'seethe', chord: 'SAO*ET' },
        { word: 'shark', chord: 'SHARBG' },
        { word: 'sheesh', chord: 'SHAOERB' },
        { word: 'shim', chord: 'SHEUPM' },
        { word: 'shock', chord: 'SHOBG' },
        { word: 'shrine', chord: 'SHRAOEUPB' },
        { word: 'shrivel', chord: 'SHREUFL' },
        { word: 'shrewd', chord: 'SHRAOUD' },
        { word: 'shuck', chord: 'SHUBG' },
        { word: 'shush', chord: 'SHURB' },
        { word: 'sleuth', chord: 'SHRAO*UT' },
        { word: 'slime', chord: 'SHRAOEUPL' },
        { word: 'slouch', chord: 'SHROUFP' },
        { word: 'smooch', chord: 'SPHAOFP' },
        { word: 'splotch', chord: 'SPHROFP' },
        { word: 'sugar', chord: 'SHAOURG' },
        { word: 'them', chord: 'THEPL' },
        { word: 'thence', chord: 'THEPBS' },
        { word: 'thing', chord: 'THEUPBG' },
        { word: 'thrash', chord: 'THRARB' },
        { word: 'thrill', chord: 'THREUL' },
        { word: 'throng', chord: 'THROPBG' },
        { word: 'thumb', chord: 'THUPL' },
        { word: 'vouch', chord: 'SROUFP' }
    ],
    'compound-clusters': [
        { word: 'arch', chord: 'AFRPB' },
        { word: 'calc', chord: 'KA*LG' },
        { word: 'camp', chord: 'KA*PL' },
        { word: 'caption', chord: 'KAPGS' },
        { word: 'carve', chord: 'KAFRB' },
        { word: 'correction', chord: 'KREBGS' },
        { word: 'cramp', chord: 'KRA*PL' },
        { word: 'crank', chord: 'KRA*PBG' },
        { word: 'crunch', chord: 'KRUFRPB' },
        { word: 'curve', chord: 'KUFRB' },
        { word: 'cushion', chord: 'KUGS' },
        { word: 'hemp', chord: 'H*EPL' },
        { word: 'honk', chord: 'HO*PBG' },
        { word: 'hulk', chord: 'H*ULG' },
        { word: 'hunch', chord: 'HUFRPB' },
        { word: 'option', chord: 'OPGS' },
        { word: 'passion', chord: 'PAGS' },
        { word: 'pomp', chord: 'PO*PL' },
        { word: 'porch', chord: 'POFRPB' },
        { word: 'portion', chord: 'PORGS' },
        { word: 'prank', chord: 'PRA*PBG' },
        { word: 'pump', chord: 'P*UPL' },
        { word: 'quench', chord: 'KWEFRPB' },
        { word: 'ramp', chord: 'RA*PL' },
        { word: 'ranch', chord: 'RAFRPB' },
        { word: 'rank', chord: 'RA*PBG' },
        { word: 'ration', chord: 'RAGS' },
        { word: 'romp', chord: 'RO*PL' },
        { word: 'rump', chord: 'R*UPL' },
        { word: 'section', chord: 'SEBGS' },
        { word: 'serve', chord: 'SEFRB' },
        { word: 'session', chord: 'SEGS' },
        { word: 'squelch', chord: 'SKWELG' },
        { word: 'starch', chord: 'STAFRPB' },
        { word: 'starve', chord: 'STAFRB' },
        { word: 'stench', chord: 'STEFRPB' },
        { word: 'suction', chord: 'SUBGS' },
        { word: 'sulk', chord: 'S*ULG' },
        { word: 'suppression', chord: 'SPREGS' },
        { word: 'swerve', chord: 'SWEFRB' },
        { word: 'talc', chord: 'TA*LG' },
        { word: 'tamp', chord: 'TA*PL' },
        { word: 'tank', chord: 'TA*PBG' },
        { word: 'torch', chord: 'TOFRPB' },
        { word: 'trench', chord: 'TREFRPB' },
        { word: 'trump', chord: 'TR*UPL' },
        { word: 'wonk', chord: 'WO*PBG' }
    ],
    'combo-3': [
        { word: 'auction', chord: 'AUBGS' },
        { word: 'belch', chord: 'PWELG' },
        { word: 'bilge', chord: 'PWEULG' },
        { word: 'bilk', chord: 'PW*EULG' },
        { word: 'birch', chord: 'PWEUFRPB' },
        { word: 'blank', chord: 'PWHRA*PBG' },
        { word: 'blimp', chord: 'PWHR*EUPL' },
        { word: 'blink', chord: 'PWHR*EUPBG' },
        { word: 'branch', chord: 'PWRAFRPB' },
        { word: 'brink', chord: 'PWR*EUPBG' },
        { word: 'brunch', chord: 'PWRUFRPB' },
        { word: 'bulge', chord: 'PWULG' },
        { word: 'bulk', chord: 'PW*ULG' },
        { word: 'chomp', chord: 'KHO*PL' },
        { word: 'chunk', chord: 'KH*UPBG' },
        { word: 'church', chord: 'KHUFRPB' },
        { word: 'clamp', chord: 'KHRA*PL' },
        { word: 'clench', chord: 'KHREFRPB' },
        { word: 'collection', chord: 'KHREBGS' },
        { word: 'correction', chord: 'KREBGS' },
        { word: 'damp', chord: 'TKA*PL' },
        { word: 'dank', chord: 'TKA*PBG' },
        { word: 'depiction', chord: 'TKPEUBGS' },
        { word: 'drench', chord: 'TKREFRPB' },
        { word: 'drink', chord: 'TKR*EUPBG' },
        { word: 'election', chord: 'HREBGS' },
        { word: 'finch', chord: 'TPEUFRPB' },
        { word: 'flank', chord: 'TPHRA*PBG' },
        { word: 'flunk', chord: 'TPHR*UPBG' },
        { word: 'fraction', chord: 'TPRABGS' },
        { word: 'friction', chord: 'TPREUBGS' },
        { word: 'fusion', chord: 'TPAOUGS' },
        { word: 'gulch', chord: 'TKPWULG' },
        { word: 'gunk', chord: 'TKPW*UPBG' },
        { word: 'ilk', chord: '*EULG' },
        { word: 'jump', chord: 'SKWR*UPL' },
        { word: 'junk', chord: 'SKWR*UPBG' },
        { word: 'lesion', chord: 'HRAOEGS' },
        { word: 'limp', chord: 'HR*EUPL' },
        { word: 'link', chord: 'HR*EUPBG' },
        { word: 'lotion', chord: 'HROEGS' },
        { word: 'lurch', chord: 'HRUFRPB' },
        { word: 'lynch', chord: 'HREUFRPB' },
        { word: 'march', chord: 'PHAFRPB' },
        { word: 'marvel', chord: 'PHAFRBL' },
        { word: 'milk', chord: 'PH*EULG' },
        { word: 'mink', chord: 'PH*EUPBG' },
        { word: 'mission', chord: 'PHEUGS' },
        { word: 'motion', chord: 'PHOEGS' },
        { word: 'mulch', chord: 'PHULG' },
        { word: 'nerve', chord: 'TPHEFRB' },
        { word: 'operation', chord: 'PRAEUGS' },
        { word: 'pillage', chord: 'PEULG' },
        { word: 'plank', chord: 'PHRA*PBG' },
        { word: 'pollution', chord: 'PHRAOUGS' },
        { word: 'provision', chord: 'PREUFGS' },
        { word: 'seduction', chord: 'STKUBGS' },
        { word: 'selection', chord: 'SHREBGS' },
        { word: 'shrimp', chord: 'SHR*EUPL' },
        { word: 'silk', chord: 'S*EULG' },
        { word: 'slump', chord: 'SHR*UPL' },
        { word: 'verve', chord: 'SREFRB' },
        { word: 'village', chord: 'SREULG' },
        { word: 'wink', chord: 'W*EUPBG' }
    ],
    '100-common-briefs': [
        { word: 'a', chord: 'AEU' },
        { word: 'about', chord: 'PW' },
        { word: 'actually', chord: 'TWAEUL' },
        { word: 'after', chord: 'AF' },
        { word: 'against', chord: 'TKPWEPBS' },
        { word: 'almost', chord: 'HR-PL' },
        { word: 'amount', chord: 'APLT' },
        { word: 'another', chord: 'TPHOER' },
        { word: 'any', chord: 'TPHEU' },
        { word: 'anything', chord: 'TPHEUG' },
        { word: 'are', chord: 'R-' },
        { word: 'ask', chord: 'SK' },
        { word: 'be', chord: 'B' },
        { word: 'became', chord: 'PWAEUPL' },
        { word: 'because', chord: 'PWAUS' },
        { word: 'become', chord: 'PW-BG' },
        { word: 'becomes', chord: 'PW-BGS' },
        { word: 'been', chord: 'PWPB' },
        { word: 'before', chord: 'PW-F' },
        { word: 'beginning', chord: 'TKPWEUPBG' },
        { word: 'being', chord: '-BG' },
        { word: 'by', chord: 'PWEU' },
        { word: 'can', chord: 'K' },
        { word: 'continue', chord: 'T-PB' },
        { word: 'continued', chord: 'T-PBD' },
        { word: 'could', chord: 'KO' },
        { word: 'describe', chord: 'SKREU' },
        { word: 'described', chord: 'SKREUD' },
        { word: 'do', chord: 'TKO' },
        { word: 'easy', chord: 'EZ' },
        { word: 'even', chord: 'AOEPB' },
        { word: 'ever', chord: '-FR' },
        { word: 'every', chord: 'EFR' },
        { word: 'example', chord: 'KP-PL' },
        { word: 'have', chord: 'SR' },
        { word: 'having', chord: 'SR-G' },
        { word: 'he', chord: 'E' },
        { word: 'I', chord: 'EU' },
        { word: 'idea', chord: 'KWR-D' },
        { word: 'ideas', chord: 'KWR-DZ' },
        { word: 'if', chord: 'TP' },
        { word: 'in', chord: 'TPH' },
        { word: 'include', chord: 'KHRU' },
        { word: 'included', chord: 'KHRUD' },
        { word: 'including', chord: 'KHRUG' },
        { word: 'includes', chord: 'KHRUS' },
        { word: 'interest', chord: 'TR' },
        { word: 'is', chord: 'S-' },
        { word: 'many', chord: 'PHAEPB' },
        { word: 'move', chord: 'PHOF' },
        { word: 'new', chord: 'TPHU' },
        { word: 'of', chord: 'F' },
        { word: 'only', chord: 'OEPBL' },
        { word: 'opinion', chord: 'P-PB' },
        { word: 'other', chord: 'OER' },
        { word: 'others', chord: 'OERS' },
        { word: 'otherwise', chord: 'O*ERZ' },
        { word: 'probably', chord: 'PROBL' },
        { word: 'question', chord: 'KWE' },
        { word: 'receive', chord: 'SAOEF' },
        { word: 'received', chord: 'SAOEFD' },
        { word: 'said', chord: 'SAEUD' },
        { word: 'somebody', chord: 'S-B' },
        { word: 'somehow', chord: 'SPHOU' },
        { word: 'someone', chord: 'SPH-PB' },
        { word: 'someplace', chord: 'SPHRAEUS' },
        { word: 'something', chord: 'S-G' },
        { word: 'sometimes', chord: 'STAOEUPLS' },
        { word: 'somewhere', chord: 'SWR' },
        { word: 'that', chord: 'THA' },
        { word: 'the', chord: '-T' },
        { word: 'there', chord: 'THR' },
        { word: 'therefore', chord: 'THR-FR' },
        { word: 'they', chord: 'THE' },
        { word: 'this', chord: 'TH' },
        { word: 'through', chord: 'THRU' },
        { word: 'to', chord: 'TO' },
        { word: 'today', chord: 'TOED' },
        { word: 'two', chord: 'TWO' },
        { word: 'understand', chord: 'URPBD' },
        { word: 'understanding', chord: 'URPBGD' },
        { word: 'unless', chord: 'TPH-LS' },
        { word: 'upon', chord: 'POPB' },
        { word: 'very', chord: 'SRE' },
        { word: 'were', chord: 'WR' },
        { word: 'what', chord: 'WHA' },
        { word: 'where', chord: 'W-R' },
        { word: 'whether', chord: 'WHR' },
        { word: 'which', chord: 'WEU' },
        { word: 'who', chord: 'WHO' },
        { word: 'with', chord: 'W' },
        { word: 'within', chord: 'W-PB' },
        { word: 'without', chord: 'WOUT' },
        { word: 'would', chord: 'WO' },
        { word: 'yes', chord: 'KWRE' },
        { word: 'you', chord: 'U' },
        { word: "you'd", chord: 'UD' },
        { word: "you'll", chord: 'UL' },
        { word: "you're", chord: 'UR' },
        { word: "you've", chord: 'UF' }
    ],
    'sentences-1': [
        { sentence: 'the cat is hot', words: ['the', 'cat', 'is', 'hot'], chords: ['-T', 'KAT', 'S-', 'HOT'] },
        { sentence: 'he has a cap', words: ['he', 'has', 'a', 'cap'], chords: ['E', 'HAZ', 'AEU', 'KAP'] },
        { sentence: 'you can cut the rag', words: ['you', 'can', 'cut', 'the', 'rag'], chords: ['U', 'K', 'KUT', '-T', 'RAG'] },
        { sentence: 'I have a new car', words: ['I', 'have', 'a', 'new', 'car'], chords: ['EU', 'SR', 'AEU', 'TPHU', 'KAR'] },
        { sentence: 'this is very easy', words: ['this', 'is', 'very', 'easy'], chords: ['TH', 'S-', 'SRE', 'EZ'] },
        { sentence: 'the cop had a hat', words: ['the', 'cop', 'had', 'a', 'hat'], chords: ['-T', 'KOP', 'HAD', 'AEU', 'HAT'] },
        { sentence: 'he said yes', words: ['he', 'said', 'yes'], chords: ['E', 'SAEUD', 'KWRE'] },
        { sentence: 'they are in the cab', words: ['they', 'are', 'in', 'the', 'cab'], chords: ['THE', 'R-', 'TPH', '-T', 'KAB'] },
        { sentence: 'you could ask about that', words: ['you', 'could', 'ask', 'about', 'that'], chords: ['U', 'KO', 'SK', 'PW', 'THA'] },
        { sentence: 'the pup is wet', words: ['the', 'pup', 'is', 'wet'], chords: ['-T', 'PUP', 'S-', 'WET'] },
        { sentence: 'I would pull the rope', words: ['I', 'would', 'pull', 'the', 'rope'], chords: ['EU', 'WO', 'PULL', '-T', 'ROEP'] },
        { sentence: 'he can tell the tale', words: ['he', 'can', 'tell', 'the', 'tale'], chords: ['E', 'K', 'TEL', '-T', 'TAEL'] },
        { sentence: 'there is a rat', words: ['there', 'is', 'a', 'rat'], chords: ['THR', 'S-', 'AEU', 'RAT'] },
        { sentence: 'they have been here', words: ['they', 'have', 'been', 'here'], chords: ['THE', 'SR', 'PWPB', 'HAOER'] },
        { sentence: 'you are with somebody', words: ['you', 'are', 'with', 'somebody'], chords: ['U', 'R-', 'W', 'S-B'] },
        { sentence: 'what do you do', words: ['what', 'do', 'you', 'do'], chords: ['WHA', 'TKO', 'U', 'TKO'] },
        { sentence: 'he had two hats', words: ['he', 'had', 'two', 'hats'], chords: ['E', 'HAD', 'TWO', 'HATS'] },
        { sentence: 'the rat sat', words: ['the', 'rat', 'sat'], chords: ['-T', 'RAT', 'SAT'] },
        { sentence: 'if you can', words: ['if', 'you', 'can'], chords: ['TP', 'U', 'K'] },
        { sentence: 'this is the core', words: ['this', 'is', 'the', 'core'], chords: ['TH', 'S-', '-T', 'KOR'] },
        { sentence: 'I said it was rough', words: ['I', 'said', 'it', 'was', 'rough'], chords: ['EU', 'SAEUD', 'T', 'WAS', 'RUF'] },
        { sentence: 'they were here before', words: ['they', 'were', 'here', 'before'], chords: ['THE', 'WR', 'HAOER', 'PW-F'] },
        { sentence: 'you have a pet', words: ['you', 'have', 'a', 'pet'], chords: ['U', 'SR', 'AEU', 'PET'] },
        { sentence: 'he can sell the rug', words: ['he', 'can', 'sell', 'the', 'rug'], chords: ['E', 'K', 'SEL', '-T', 'RUG'] },
        { sentence: 'where is the cup', words: ['where', 'is', 'the', 'cup'], chords: ['W-R', 'S-', '-T', 'KUP'] },
        { sentence: 'I have an idea', words: ['I', 'have', 'an', 'idea'], chords: ['EU', 'SR', 'APB', 'KWR-D'] },
        { sentence: 'she is in the pub', words: ['she', 'is', 'in', 'the', 'pub'], chords: ['SHAO', 'S-', 'TPH', '-T', 'PUB'] },
        { sentence: 'you would be sad', words: ['you', 'would', 'be', 'sad'], chords: ['U', 'WO', 'B', 'SAD'] },
        { sentence: 'that is the web', words: ['that', 'is', 'the', 'web'], chords: ['THA', 'S-', '-T', 'WEB'] },
        { sentence: 'every tap was red', words: ['every', 'tap', 'was', 'red'], chords: ['EFR', 'TAP', 'WAS', 'RED'] },
        { sentence: 'he had a peg', words: ['he', 'had', 'a', 'peg'], chords: ['E', 'HAD', 'AEU', 'PEG'] },
        { sentence: 'it is through the top', words: ['it', 'is', 'through', 'the', 'top'], chords: ['T', 'S-', 'THRU', '-T', 'TOP'] },
        { sentence: 'there were many rags', words: ['there', 'were', 'many', 'rags'], chords: ['THR', 'WR', 'PHAEPB', 'RAGS'] },
        { sentence: 'I can sob', words: ['I', 'can', 'sob'], chords: ['EU', 'K', 'SOB'] },
        { sentence: 'what if he cut', words: ['what', 'if', 'he', 'cut'], chords: ['WHA', 'TP', 'E', 'KUT'] },
        { sentence: 'you could have any', words: ['you', 'could', 'have', 'any'], chords: ['U', 'KO', 'SR', 'TPHEU'] },
        { sentence: 'without the tag', words: ['without', 'the', 'tag'], chords: ['WOUT', '-T', 'TAG'] },
        { sentence: 'whether it is a cab', words: ['whether', 'it', 'is', 'a', 'cab'], chords: ['WHR', 'T', 'S-', 'AEU', 'KAB'] },
        { sentence: 'the tub is hot', words: ['the', 'tub', 'is', 'hot'], chords: ['-T', 'TUB', 'S-', 'HOT'] },
        { sentence: 'he has the sap', words: ['he', 'has', 'the', 'sap'], chords: ['E', 'HAZ', '-T', 'SAP'] },
        { sentence: 'you are in a rut', words: ['you', 'are', 'in', 'a', 'rut'], chords: ['U', 'R-', 'TPH', 'AEU', 'RUT'] },
        { sentence: 'I would be there', words: ['I', 'would', 'be', 'there'], chords: ['EU', 'WO', 'B', 'THR'] },
        { sentence: 'this has been easy', words: ['this', 'has', 'been', 'easy'], chords: ['TH', 'HAZ', 'PWPB', 'EZ'] },
        { sentence: 'because of the cat', words: ['because', 'of', 'the', 'cat'], chords: ['PWAUS', 'F', '-T', 'KAT'] },
        { sentence: 'even in the hut', words: ['even', 'in', 'the', 'hut'], chords: ['AOEPB', 'TPH', '-T', 'HUT'] },
        { sentence: 'they were with us', words: ['they', 'were', 'with', 'us'], chords: ['THE', 'WR', 'W', 'US'] },
        { sentence: 'upon the rug', words: ['upon', 'the', 'rug'], chords: ['POPB', '-T', 'RUG'] },
        { sentence: 'you have something new', words: ['you', 'have', 'something', 'new'], chords: ['U', 'SR', 'S-G', 'TPHU'] },
        { sentence: 'who is the cop', words: ['who', 'is', 'the', 'cop'], chords: ['WHO', 'S-', '-T', 'KOP'] },
        { sentence: 'after the pot was set', words: ['after', 'the', 'pot', 'was', 'set'], chords: ['AF', '-T', 'POT', 'WAS', 'SET'] }
    ],
    'sentences-2': [
        { sentence: 'I would ask about the rank', words: ['I', 'would', 'ask', 'about', 'the', 'rank'], chords: ['EU', 'WO', 'SK', 'PW', '-T', 'RA*PBG'] },
        { sentence: 'somebody must carve the fish', words: ['somebody', 'must', 'carve', 'the', 'fish'], chords: ['S-B', 'PHUFT', 'KAFRB', '-T', 'TPEURB'] },
        { sentence: 'he can continue without any nerve', words: ['he', 'can', 'continue', 'without', 'any', 'nerve'], chords: ['E', 'K', 'T-PB', 'WOUT', 'TPHEU', 'TPHEFRB'] },
        { sentence: 'many are in the session', words: ['many', 'are', 'in', 'the', 'session'], chords: ['PHAEPB', 'R-', 'TPH', '-T', 'SEGS'] },
        { sentence: 'they said something about the jumps', words: ['they', 'said', 'something', 'about', 'the', 'jumps'], chords: ['THE', 'SAEUD', 'S-G', 'PW', '-T', 'SKWR*UPLS'] },
        { sentence: 'you have been with the grunt', words: ['you', 'have', 'been', 'with', 'the', 'grunt'], chords: ['U', 'SR', 'PWPB', 'W', '-T', 'TKPWRUPBT'] },
        { sentence: 'I could describe the village very well', words: ['I', 'could', 'describe', 'the', 'village', 'very', 'well'], chords: ['EU', 'KO', 'SKREU', '-T', 'SREULG', 'SRE', 'WEL'] },
        { sentence: 'he had only one idea', words: ['he', 'had', 'only', 'one', 'idea'], chords: ['E', 'HAD', 'OEPBL', 'WUPB', 'KWR-D'] },
        { sentence: 'the cop can serve with interest', words: ['the', 'cop', 'can', 'serve', 'with', 'interest'], chords: ['-T', 'KOP', 'K', 'SEFRB', 'W', 'TR'] },
        { sentence: 'somebody would receive the ration', words: ['somebody', 'would', 'receive', 'the', 'ration'], chords: ['S-B', 'WO', 'SAOEF', '-T', 'RAGS'] },
        { sentence: 'they must include the option', words: ['they', 'must', 'include', 'the', 'option'], chords: ['THE', 'PHUFT', 'KHRU', '-T', 'OPGS'] },
        { sentence: 'I have an opinion about the hulk', words: ['I', 'have', 'an', 'opinion', 'about', 'the', 'hulk'], chords: ['EU', 'SR', 'APB', 'P-PB', 'PW', '-T', 'H*ULG'] },
        { sentence: 'can you move the bulge', words: ['can', 'you', 'move', 'the', 'bulge'], chords: ['K', 'U', 'PHOF', '-T', 'PWULG'] },
        { sentence: 'he was upon the ramp', words: ['he', 'was', 'upon', 'the', 'ramp'], chords: ['E', 'WAS', 'POPB', '-T', 'RA*PL'] },
        { sentence: 'they are within the porch', words: ['they', 'are', 'within', 'the', 'porch'], chords: ['THE', 'R-', 'W-PB', '-T', 'POFRPB'] },
        { sentence: 'somebody had to become the donor', words: ['somebody', 'had', 'to', 'become', 'the', 'donor'], chords: ['S-B', 'HAD', 'TO', 'PW-BG', '-T', 'TKOERPB'] },
        { sentence: 'we could have the potion', words: ['we', 'could', 'have', 'the', 'potion'], chords: ['WE', 'KO', 'SR', '-T', 'POEGS'] },
        { sentence: 'he had a question about the nerve', words: ['he', 'had', 'a', 'question', 'about', 'the', 'nerve'], chords: ['E', 'HAD', 'AEU', 'KWE', 'PW', '-T', 'TPHEFRB'] },
        { sentence: 'you would move only with the grant', words: ['you', 'would', 'move', 'only', 'with', 'the', 'grant'], chords: ['U', 'WO', 'PHOF', 'OEPBL', 'W', '-T', 'TKPWRAPBT'] },
        { sentence: 'I can include many of the fish', words: ['I', 'can', 'include', 'many', 'of', 'the', 'fish'], chords: ['EU', 'K', 'KHRU', 'PHAEPB', 'F', '-T', 'TPEURB'] },
        { sentence: 'they said someone had the sulk', words: ['they', 'said', 'someone', 'had', 'the', 'sulk'], chords: ['THE', 'SAEUD', 'SPH-PB', 'HAD', '-T', 'S*ULG'] },
        { sentence: 'he had a new interest', words: ['he', 'had', 'a', 'new', 'interest'], chords: ['E', 'HAD', 'AEU', 'TPHU', 'TR'] },
        { sentence: 'you must serve the others', words: ['you', 'must', 'serve', 'the', 'others'], chords: ['U', 'PHUFT', 'SEFRB', '-T', 'OERS'] },
        { sentence: 'because of the cramp in the leg', words: ['because', 'of', 'the', 'cramp', 'in', 'the', 'leg'], chords: ['PWAUS', 'F', '-T', 'KRA*PL', 'TPH', '-T', 'HREBG'] },
        { sentence: 'they could receive the passion', words: ['they', 'could', 'receive', 'the', 'passion'], chords: ['THE', 'KO', 'SAOEF', '-T', 'PAGS'] },
        { sentence: 'someone would become the winner', words: ['someone', 'would', 'become', 'the', 'winner'], chords: ['SPH-PB', 'WO', 'PW-BG', '-T', 'WEURPB'] },
        { sentence: 'I have to ask about the clamp', words: ['I', 'have', 'to', 'ask', 'about', 'the', 'clamp'], chords: ['EU', 'SR', 'TO', 'SK', 'PW', '-T', 'KHRA*PL'] },
        { sentence: 'he was upon the tank', words: ['he', 'was', 'upon', 'the', 'tank'], chords: ['E', 'WAS', 'POPB', '-T', 'TA*PBG'] },
        { sentence: 'you can move with the marvel', words: ['you', 'can', 'move', 'with', 'the', 'marvel'], chords: ['U', 'K', 'PHOF', 'W', '-T', 'PHAFRBL'] },
        { sentence: 'they would ask the question', words: ['they', 'would', 'ask', 'the', 'question'], chords: ['THE', 'WO', 'SK', '-T', 'KWE'] },
        { sentence: 'somebody must have the curve', words: ['somebody', 'must', 'have', 'the', 'curve'], chords: ['S-B', 'PHUFT', 'SR', '-T', 'KUFRB'] },
        { sentence: 'I could describe the junction very well', words: ['I', 'could', 'describe', 'the', 'junction', 'very', 'well'], chords: ['EU', 'KO', 'SKREU', '-T', 'SKWRUPBGS', 'SRE', 'WEL'] },
        { sentence: 'he has been within the gulch', words: ['he', 'has', 'been', 'within', 'the', 'gulch'], chords: ['E', 'HAZ', 'PWPB', 'W-PB', '-T', 'TKPWULG'] },
        { sentence: 'you have to continue the dunk', words: ['you', 'have', 'to', 'continue', 'the', 'dunk'], chords: ['U', 'SR', 'TO', 'T-PB', '-T', 'TKU*PBG'] },
        { sentence: 'many had an opinion about the nerve', words: ['many', 'had', 'an', 'opinion', 'about', 'the', 'nerve'], chords: ['PHAEPB', 'HAD', 'APB', 'P-PB', 'PW', '-T', 'TPHEFRB'] },
        { sentence: 'I would receive only the option', words: ['I', 'would', 'receive', 'only', 'the', 'option'], chords: ['EU', 'WO', 'SAOEF', 'OEPBL', '-T', 'OPGS'] },
        { sentence: 'the cop must serve with the trunk', words: ['the', 'cop', 'must', 'serve', 'with', 'the', 'trunk'], chords: ['-T', 'KOP', 'PHUFT', 'SEFRB', 'W', '-T', 'TRU*PBG'] },
        { sentence: 'they had to include the suction', words: ['they', 'had', 'to', 'include', 'the', 'suction'], chords: ['THE', 'HAD', 'TO', 'KHRU', '-T', 'SUBGS'] },
        { sentence: 'someone can move the jar', words: ['someone', 'can', 'move', 'the', 'jar'], chords: ['SPH-PB', 'K', 'PHOF', '-T', 'SKWRAR'] },
        { sentence: 'you have something new about the nerve', words: ['you', 'have', 'something', 'new', 'about', 'the', 'nerve'], chords: ['U', 'SR', 'S-G', 'TPHU', 'PW', '-T', 'TPHEFRB'] },
        { sentence: 'he must ask the question', words: ['he', 'must', 'ask', 'the', 'question'], chords: ['E', 'PHUFT', 'SK', '-T', 'KWE'] },
        { sentence: 'I could have the passion', words: ['I', 'could', 'have', 'the', 'passion'], chords: ['EU', 'KO', 'SR', '-T', 'PAGS'] },
        { sentence: 'they are within the ranch', words: ['they', 'are', 'within', 'the', 'ranch'], chords: ['THE', 'R-', 'W-PB', '-T', 'RAFRPB'] },
        { sentence: 'someone would receive the marvel', words: ['someone', 'would', 'receive', 'the', 'marvel'], chords: ['SPH-PB', 'WO', 'SAOEF', '-T', 'PHAFRBL'] },
        { sentence: 'he had an idea about the bulk', words: ['he', 'had', 'an', 'idea', 'about', 'the', 'bulk'], chords: ['E', 'HAD', 'APB', 'KWR-D', 'PW', '-T', 'PW*ULG'] },
        { sentence: 'you must include the correction', words: ['you', 'must', 'include', 'the', 'correction'], chords: ['U', 'PHUFT', 'KHRU', '-T', 'KREBGS'] },
        { sentence: 'many can continue with the session', words: ['many', 'can', 'continue', 'with', 'the', 'session'], chords: ['PHAEPB', 'K', 'T-PB', 'W', '-T', 'SEGS'] },
        { sentence: 'I have to describe the option', words: ['I', 'have', 'to', 'describe', 'the', 'option'], chords: ['EU', 'SR', 'TO', 'SKREU', '-T', 'OPGS'] },
        { sentence: 'someone had the nerve to jump', words: ['someone', 'had', 'the', 'nerve', 'to', 'jump'], chords: ['SPH-PB', 'HAD', '-T', 'TPHEFRB', 'TO', 'SKWR*UPL'] },
        { sentence: 'you would become the donor', words: ['you', 'would', 'become', 'the', 'donor'], chords: ['U', 'WO', 'PW-BG', '-T', 'TKOERPB'] }
    ],
    'sentences-3': [
        { sentence: 'the church steeple reached through the autumn sky', words: ['the', 'church', 'steeple', 'reached', 'through', 'the', 'autumn', 'sky'], chords: ['-T', 'KHUFRPB', 'STAOEP/-L', 'RAOEFP/-D', 'THRU', '-T', 'AU/TUPB', 'SKEU'] },
        { sentence: 'actually I would suppress the corruption within', words: ['actually', 'I', 'would', 'suppress', 'the', 'corruption', 'within'], chords: ['TWAEUL', 'EU', 'WO', 'SPREGS', '-T', 'KRUPGS', 'W-PB'] },
        { sentence: 'whether they received the provision or not', words: ['whether', 'they', 'received', 'the', 'provision', 'or', 'not'], chords: ['WHR', 'THE', 'SAOEFD', '-T', 'PREUFGS', 'OR', 'TPHOT'] },
        { sentence: 'somebody described the sprawling pollution before', words: ['somebody', 'described', 'the', 'sprawling', 'pollution', 'before'], chords: ['S-B', 'SKREUD', '-T', 'SPRAUL/-G', 'PHRAOUGS', 'PW-F'] },
        { sentence: 'the shrivel began through every splotch', words: ['the', 'shrivel', 'began', 'through', 'every', 'splotch'], chords: ['-T', 'SHREUFL', 'PWAEPB', 'THRU', 'EFR', 'SPHROFP'] },
        { sentence: 'they continued with the diphthong examples', words: ['they', 'continued', 'with', 'the', 'diphthong', 'examples'], chords: ['THE', 'T-PBD', 'W', '-T', 'TKEUF/THOPBG', 'KP-PLS'] },
        { sentence: 'unless you understand the seduction it becomes difficult', words: ['unless', 'you', 'understand', 'the', 'seduction', 'it', 'becomes', 'difficult'], chords: ['TPH-LS', 'U', 'URPBD', '-T', 'STKUBGS', 'T', 'PW-BGS', 'TKEUF/KULT'] },
        { sentence: 'the blimp squeezed through the awful weather', words: ['the', 'blimp', 'squeezed', 'through', 'the', 'awful', 'weather'], chords: ['-T', 'PWHR*EUPL', 'SKWAOES/-D', 'THRU', '-T', 'AUFL', 'W*ER'] },
        { sentence: 'having stung the prowler they scattered elsewhere', words: ['having', 'stung', 'the', 'prowler', 'they', 'scattered', 'elsewhere'], chords: ['SR-G', 'STUPBG', '-T', 'PROUL/-ER', 'THE', 'SKAEURT/-D', 'ELS/W-R'] },
        { sentence: 'many probably received the faction against friction', words: ['many', 'probably', 'received', 'the', 'faction', 'against', 'friction'], chords: ['PHAEPB', 'PROBL', 'SAOEFD', '-T', 'TPABGS', 'TKPWEPBS', 'TPREUBGS'] },
        { sentence: 'the depiction included somebody slouching somehow', words: ['the', 'depiction', 'included', 'somebody', 'slouching', 'somehow'], chords: ['-T', 'TKPEUBGS', 'KHRUD', 'S-B', 'SHROUFP/-G', 'SPHOU'] },
        { sentence: 'therefore the election results caused strong interest', words: ['therefore', 'the', 'election', 'results', 'caused', 'strong', 'interest'], chords: ['THR-FR', '-T', 'HREBGS', 'RAOULTS', 'KAUS/-D', 'STROPBG', 'TR'] },
        { sentence: 'the beginning question was about the trench', words: ['the', 'beginning', 'question', 'was', 'about', 'the', 'trench'], chords: ['-T', 'TKPWEUPBG', 'KWE', 'WAS', 'PW', '-T', 'TREFRPB'] },
        { sentence: 'they marched upon the starch with others', words: ['they', 'marched', 'upon', 'the', 'starch', 'with', 'others'], chords: ['THE', 'PHAFRPB/-D', 'POPB', '-T', 'STAFRPB', 'W', 'OERS'] },
        { sentence: 'otherwise the collection would starve without correction', words: ['otherwise', 'the', 'collection', 'would', 'starve', 'without', 'correction'], chords: ['O*ERZ', '-T', 'KHREBGS', 'WO', 'STAFRB', 'WOUT', 'KREBGS'] },
        { sentence: 'the shrimp drench splattered against the wealth', words: ['the', 'shrimp', 'drench', 'splattered', 'against', 'the', 'wealth'], chords: ['-T', 'SHR*EUPL', 'TKREFRPB', 'SPLAEURT/-D', 'TKPWEPBS', '-T', 'W*ELT'] },
        { sentence: 'actually there were several auctions upon completion', words: ['actually', 'there', 'were', 'several', 'auctions', 'upon', 'completion'], chords: ['TWAEUL', 'THR', 'WR', 'SEFRL', 'AUBGSS', 'POPB', 'KPHLAOEGS'] },
        { sentence: 'somebody said the treble quench began today', words: ['somebody', 'said', 'the', 'treble', 'quench', 'began', 'today'], chords: ['S-B', 'SAEUD', '-T', 'TREBL', 'KWEFRPB', 'PWAEPB', 'TOED'] },
        { sentence: 'the blush became visible through every glimpse', words: ['the', 'blush', 'became', 'visible', 'through', 'every', 'glimpse'], chords: ['-T', 'PWHRURB', 'PWAEUPL', 'SREUZ/-BL', 'THRU', 'EFR', 'TKPWHREUPLS'] },
        { sentence: 'whether they understood the notion or received ideas', words: ['whether', 'they', 'understood', 'the', 'notion', 'or', 'received', 'ideas'], chords: ['WHR', 'THE', 'URPBGD', '-T', 'TPHOEGS', 'OR', 'SAOEFD', 'KWR-DZ'] },
        { sentence: 'the junction seduction caused much destruction somewhere', words: ['the', 'junction', 'seduction', 'caused', 'much', 'destruction', 'somewhere'], chords: ['-T', 'SKWRUPBGS', 'STKUBGS', 'KAUS/-D', 'PHUFP', 'TKRUBGS', 'SWR'] },
        { sentence: 'they probably included the ruffled portion', words: ['they', 'probably', 'included', 'the', 'ruffled', 'portion'], chords: ['THE', 'PROBL', 'KHRUD', '-T', 'RUFLD', 'PORGS'] },
        { sentence: 'actually the thrust through the gulch succeeded', words: ['actually', 'the', 'thrust', 'through', 'the', 'gulch', 'succeeded'], chords: ['TWAEUL', '-T', 'THRUFT', 'THRU', '-T', 'TKPWULG', 'SKAOED/-D'] },
        { sentence: 'someone described the beginning average upon request', words: ['someone', 'described', 'the', 'beginning', 'average', 'upon', 'request'], chords: ['SPH-PB', 'SKREUD', '-T', 'TKPWEUPBG', 'AFRGS', 'POPB', 'RAOUBGS'] },
        { sentence: 'the blink revealed the amount through compression', words: ['the', 'blink', 'revealed', 'the', 'amount', 'through', 'compression'], chords: ['-T', 'PWHR*EUPBG', 'RAOEFLD', '-T', 'APLT', 'THRU', 'KPHREGS'] },
        { sentence: 'they moved within the splotch without understanding', words: ['they', 'moved', 'within', 'the', 'splotch', 'without', 'understanding'], chords: ['THE', 'PHOF/-D', 'W-PB', '-T', 'SPHROFP', 'WOUT', 'URPBGD'] },
        { sentence: 'many continued the discussion until the semester ended', words: ['many', 'continued', 'the', 'discussion', 'until', 'the', 'semester', 'ended'], chords: ['PHAEPB', 'T-PBD', '-T', 'STKUBGS', 'UPB/TEUL', '-T', 'SPHEFRT', 'EPB/-D'] },
        { sentence: 'therefore the sculpture displayed something absolutely fresh', words: ['therefore', 'the', 'sculpture', 'displayed', 'something', 'absolutely', 'fresh'], chords: ['THR-FR', '-T', 'SKULPT/-UR', 'TKPLA*EU/-D', 'S-G', 'ABSAOULT/-LI', 'TPRERB'] },
        { sentence: 'someone crushed the squelch during the thrust', words: ['someone', 'crushed', 'the', 'squelch', 'during', 'the', 'thrust'], chords: ['SPH-PB', 'KRURB/-D', '-T', 'SKWELG', 'TKOURPBG', '-T', 'THRUFT'] },
        { sentence: 'the opinion became clear through several examples', words: ['the', 'opinion', 'became', 'clear', 'through', 'several', 'examples'], chords: ['-T', 'P-PB', 'PWAEUPL', 'KHRAOR', 'THRU', 'SEFRL', 'KP-PLS'] },
        { sentence: 'whether anybody starves or receives the session', words: ['whether', 'anybody', 'starves', 'or', 'receives', 'the', 'session'], chords: ['WHR', 'TPHAOEPB', 'STAFRBS', 'OR', 'SAOEUFZ', '-T', 'SEGS'] },
        { sentence: 'actually the correction suppressed every erroneous notion', words: ['actually', 'the', 'correction', 'suppressed', 'every', 'erroneous', 'notion'], chords: ['TWAEUL', '-T', 'KREBGS', 'SPREGS/-D', 'EFR', 'ROEPBS', 'TPHOEGS'] },
        { sentence: 'they marched through the stench without hesitation', words: ['they', 'marched', 'through', 'the', 'stench', 'without', 'hesitation'], chords: ['THE', 'PHAFRPB/-D', 'THRU', '-T', 'STEFRPB', 'WOUT', 'HEFS/TAEUGS'] },
        { sentence: 'the provision included the clutch and junction', words: ['the', 'provision', 'included', 'the', 'clutch', 'and', 'junction'], chords: ['-T', 'PREUFGS', 'KHRUD', '-T', 'KHRUFP', 'SKP', 'SKWRUPBGS'] },
        { sentence: 'somebody described the pillage with much passion', words: ['somebody', 'described', 'the', 'pillage', 'with', 'much', 'passion'], chords: ['S-B', 'SKREUD', '-T', 'PEULG', 'W', 'PHUFP', 'PAGS'] },
        { sentence: 'therefore the flunk resulted in another question', words: ['therefore', 'the', 'flunk', 'resulted', 'in', 'another', 'question'], chords: ['THR-FR', '-T', 'TPHR*UPBG', 'RAOULTD', 'TPH', 'TPHOER', 'KWE'] },
        { sentence: 'many of the limp verve sparkled through', words: ['many', 'of', 'the', 'limp', 'verve', 'sparkled', 'through'], chords: ['PHAEPB', 'F', '-T', 'HR*EUPL', 'SREFRB', 'SPARBGLD', 'THRU'] },
        { sentence: 'the dank brunch scuffled against the ranch', words: ['the', 'dank', 'brunch', 'scuffled', 'against', 'the', 'ranch'], chords: ['-T', 'TKA*PBG', 'PWRUFRPB', 'SKUFLD', 'TKPWEPBS', '-T', 'RAFRPB'] },
        { sentence: 'whether somebody includes the depiction or not', words: ['whether', 'somebody', 'includes', 'the', 'depiction', 'or', 'not'], chords: ['WHR', 'S-B', 'KHRUS', '-T', 'TKPEUBGS', 'OR', 'TPHOT'] },
        { sentence: 'the thrust through the birch revealed corruption', words: ['the', 'thrust', 'through', 'the', 'birch', 'revealed', 'corruption'], chords: ['-T', 'THRUFT', 'THRU', '-T', 'PWEUFRPB', 'RAOEFLD', 'KRUPGS'] },
        { sentence: 'they received the smuggle through several channels', words: ['they', 'received', 'the', 'smuggle', 'through', 'several', 'channels'], chords: ['THE', 'SAOEFD', '-T', 'SPHULG', 'THRU', 'SEFRL', 'KHAPBLS'] },
        { sentence: 'actually there were many qualms about continuing', words: ['actually', 'there', 'were', 'many', 'qualms', 'about', 'continuing'], chords: ['TWAEUL', 'THR', 'WR', 'PHAEPB', 'KWAPLS', 'PW', 'T-PBGD'] },
        { sentence: 'the gleam sparkled upon the crunch', words: ['the', 'gleam', 'sparkled', 'upon', 'the', 'crunch'], chords: ['-T', 'TKPWHRAOEM', 'SPARBGLD', 'POPB', '-T', 'KRUFRPB'] },
        { sentence: 'someone described the twang during the session', words: ['someone', 'described', 'the', 'twang', 'during', 'the', 'session'], chords: ['SPH-PB', 'SKREUD', '-T', 'TWAPBG', 'TKOURPBG', '-T', 'SEGS'] },
        { sentence: 'therefore the suppression resulted in new ideas', words: ['therefore', 'the', 'suppression', 'resulted', 'in', 'new', 'ideas'], chords: ['THR-FR', '-T', 'SPREGS', 'RAOULTD', 'TPH', 'TPHU', 'KWR-DZ'] },
        { sentence: 'they continued through the slouch without problems', words: ['they', 'continued', 'through', 'the', 'slouch', 'without', 'problems'], chords: ['THE', 'T-PBD', 'THRU', '-T', 'SHROUFP', 'WOUT', 'PROBLZ'] },
        { sentence: 'the blimp shriveled through the awful pollution', words: ['the', 'blimp', 'shriveled', 'through', 'the', 'awful', 'pollution'], chords: ['-T', 'PWHR*EUPL', 'SHREUFL/-D', 'THRU', '-T', 'AUFL', 'PHRAOUGS'] },
        { sentence: 'many understood the beginning until the completion', words: ['many', 'understood', 'the', 'beginning', 'until', 'the', 'completion'], chords: ['PHAEPB', 'URPBGD', '-T', 'TKPWEUPBG', 'UPB/TEUL', '-T', 'KPHLAOEGS'] },
        { sentence: 'whether the drench soaked or the bleach spread', words: ['whether', 'the', 'drench', 'soaked', 'or', 'the', 'bleach', 'spread'], chords: ['WHR', '-T', 'TKREFRPB', 'SOEBG/-D', 'OR', '-T', 'PWHRAOEFP', 'SPRED'] },
        { sentence: 'the faction received the correction with much interest', words: ['the', 'faction', 'received', 'the', 'correction', 'with', 'much', 'interest'], chords: ['-T', 'TPABGS', 'SAOEFD', '-T', 'KREBGS', 'W', 'PHUFP', 'TR'] }
    ]
};
